

#ifndef LOCALTITLE_INCLUDED
#define LOCALTITLE_INCLUDED

#define LT_MacroText1 "Du miese Ratte..." 
#define LT_MacroText2 "Du bist erledigt..." 
#define LT_MacroText3 "Ich reiss Dir die Seele aus dem Leib..."

#define LT_GameCompleteWithoutCrystals "Super! Sie haben alle Level geschafft, aber nicht alle Kristalle gefunden. Sie müssen nochmal von vorn anfangen, wenn Sie die volle Belohnung möchten." 
#define LT_GameCompleteGotAllCrystalsSoFar "Super! Sie haben alle Kristalle. Sie erhalten ein Extraleben für den Geheimlevel. Für den Kristall dort gibt es eine besondere Belohnung." 
#define LT_GameCompleteWithAllCrystals "Super! Sie haben alle Kristalle. Dafür gibt es den versteckten Biker."
#define LT_GameCompleteWithAllCrystalsExceptLast "Tja, Sie haben den Geheimlevel geschafft, aber den letzten Kristall nicht geholt. Vielleicht nächstes Mal."
#define LT_GameCompleteWithCheating "Tja, Sie haben das Spiel beendet, aber nur durch Mogeln. Wenn Sie den Geheimlevel sehen und eine besondere Belohnung erhalten möchten, müssen Sie ehrlich kämpfen!"
#define LT_GameCompleteAdditionalLevels "Glückwunsch! Sie haben alle derzeitigen Zusatzlevel geschafft. Halten Sie nach weiteren Mission-Packs Ausschau!!"

#define LT_MENU_NEW_SpecialMessage0 "ok"

#define LT_MENU_NEW_NumberOfSecretsEnemys0 "ok"

#define LT_MENU_NEW_NumberOfGoldBars0 "ok"

#define LT_MENU_NEW_NumberOfCrystals0 "ok"

#define LT_MENU_NEW_StartSinglePlayer0 "Einzelspiel" 
#define LT_MENU_NEW_StartSinglePlayer1 "Start" 
#define LT_MENU_NEW_StartSinglePlayer2 "Level" 

#define LT_MENU_NEW_Error0 "ok"

#define LT_MENU_NEW_GeneralLoading0 "Ladevorgang..."

#define LT_MENU_NEW_StartAttractMode0 "Ladevorgang..."

#define LT_MENU_NEW_HostWaitingToStart0 "Warten auf Start..." 
#define LT_MENU_NEW_HostWaitingToStart1 "Start" 
#define LT_MENU_NEW_HostWaitingToStart2 "IP:" 
#define LT_MENU_NEW_HostWaitingToStart3 "Spielerzahl" 
#define LT_MENU_NEW_HostWaitingToStart4 "Nch:" 

#define LT_MENU_NEW_ValidPickups0 "Erlaubte Pickups"
#define LT_MENU_NEW_ValidPickups1 "Trojax"
#define LT_MENU_NEW_ValidPickups2 "Pyrolite"
#define LT_MENU_NEW_ValidPickups3 "Transpulse"
#define LT_MENU_NEW_ValidPickups4 "Suss-Kanone"
#define LT_MENU_NEW_ValidPickups5 "Laser"
#define LT_MENU_NEW_ValidPickups6 "Mug"
#define LT_MENU_NEW_ValidPickups7 "Solaris"
#define LT_MENU_NEW_ValidPickups8 "Scatter"
#define LT_MENU_NEW_ValidPickups9 "Gravgon"
#define LT_MENU_NEW_ValidPickups10 "MRW"
#define LT_MENU_NEW_ValidPickups11 "Titan"
#define LT_MENU_NEW_ValidPickups12 "Schebemine"
#define LT_MENU_NEW_ValidPickups13 "Raketenmine"
#define LT_MENU_NEW_ValidPickups14 "Quantummine"
#define LT_MENU_NEW_ValidPickups15 "Unverwundbarkeit"
#define LT_MENU_NEW_ValidPickups16 "Nitro"
#define LT_MENU_NEW_ValidPickups17 "Tarnmantel"
#define LT_MENU_NEW_ValidPickups18 "Orbit Pulsar"
#define LT_MENU_NEW_ValidPickups19 "Goldenes Power Pack"

#define LT_MENU_NEW_MoreMultiplayerOptions0 "Multiplayer-Optionen"
#define LT_MENU_NEW_MoreMultiplayerOptions1 "Verzög.-toleranz"
#define LT_MENU_NEW_MoreMultiplayerOptions2 "Kurze Pakete"
#define LT_MENU_NEW_MoreMultiplayerOptions3 "Paketgruppen" 
#define LT_MENU_NEW_MoreMultiplayerOptions4 "Paketrate" 
#define LT_MENU_NEW_MoreMultiplayerOptions5 "Ping zeigen" 
#define LT_MENU_NEW_MoreMultiplayerOptions6 "Ping-Abstände" 
#define LT_MENU_NEW_MoreMultiplayerOptions7 "Auspuffgase" 
#define LT_MENU_NEW_MoreMultiplayerOptions8 "Leuchtende Bikes" 
#define LT_MENU_NEW_MoreMultiplayerOptions9 "team schaden" 
#define LT_MENU_NEW_MoreMultiplayerOptions10 "Beutebonus" 
#define LT_MENU_NEW_MoreMultiplayerOptions11 "Flaggenpunkte" 
#define LT_MENU_NEW_MoreMultiplayerOptions12 "Beutebonus" 
#define LT_MENU_NEW_MoreMultiplayerOptions13 "Eigene Flagge" 
#define LT_MENU_NEW_MoreMultiplayerOptions14 "Demo aufzeichnen"
#define LT_MENU_NEW_MoreMultiplayerOptions15 "Demo-Titel"
#define LT_MENU_NEW_MoreMultiplayerOptions16 "Schaden verursacht, als..."
#define LT_MENU_NEW_MoreMultiplayerOptions17 "Ich glaube, meine Schüsse trafen dich"
#define LT_MENU_NEW_MoreMultiplayerOptions18 "Ich glaube, deine Schüsse trafen mich"
#define LT_MENU_NEW_MoreMultiplayerOptions19 "Erlaubte Pickups ändern"
#define LT_MENU_NEW_MoreMultiplayerOptions20 "Willkürliche Pickups"

#define LT_MENU_NEW_CreateGame0 "Multiplayer-Spiel erstellen"
#define LT_MENU_NEW_CreateGame1 "Spiel starten"
#define LT_MENU_NEW_CreateGame2 "IP:"
#define LT_MENU_NEW_CreateGame3 "spielname"
#define LT_MENU_NEW_CreateGame4 "Level"
#define LT_MENU_NEW_CreateGame5 "Spielerzahl"
#define LT_MENU_NEW_CreateGame6 "Punktgrenze"
#define LT_MENU_NEW_CreateGame7 "Zeitlimit"
#define LT_MENU_NEW_CreateGame8 "Spieltyp"
#define LT_MENU_NEW_CreateGame9 "Jeder gegen jeden"
#define LT_MENU_NEW_CreateGame10 "Team-Spiel"
#define LT_MENU_NEW_CreateGame11 "Eroberung der Flagge"
#define LT_MENU_NEW_CreateGame12 "Flaggenjagd"
#define LT_MENU_NEW_CreateGame13 "Beutejagd"
#define LT_MENU_NEW_CreateGame14 "Team-Beutejagd"
#define LT_MENU_NEW_CreateGame15 "Abwechseln"
#define LT_MENU_NEW_CreateGame16 "Weitere Optionen"
#define LT_MENU_NEW_CreateGame17 "Beenden"

#define LT_MENU_NEW_CreateLobbyGame0 "Multiplayer-Spiel erstellen"
#define LT_MENU_NEW_CreateLobbyGame1 "Spiel starten"
#define LT_MENU_NEW_CreateLobbyGame2 "IP:"
#define LT_MENU_NEW_CreateLobbyGame3 "Name der Sitzung"
#define LT_MENU_NEW_CreateLobbyGame4 "Level"
#define LT_MENU_NEW_CreateLobbyGame5 "Spielerzahl"
#define LT_MENU_NEW_CreateLobbyGame6 "Punktgrenze"
#define LT_MENU_NEW_CreateLobbyGame7 "Zeitlimit"
#define LT_MENU_NEW_CreateLobbyGame8 "Spieltyp"
#define LT_MENU_NEW_CreateLobbyGame9 "Jeder gegen jeden"
#define LT_MENU_NEW_CreateLobbyGame10 "Team-Spiel"
#define LT_MENU_NEW_CreateLobbyGame11 "Eroberung der Flagge"
#define LT_MENU_NEW_CreateLobbyGame12 "Beutejagd"
#define LT_MENU_NEW_CreateLobbyGame13 "Team-Beutejagd"
#define LT_MENU_NEW_CreateLobbyGame14 "Abwechseln"
#define LT_MENU_NEW_CreateLobbyGame15 "Weitere Optionen"
#define LT_MENU_NEW_CreateLobbyGame16 "Beenden"

#define LT_MENU_NEW_ChooseConnectionToStart0 "Verbindungsart wählen"

#define LT_MENU_NEW_PrimaryOrder0 "Primärwaffenauswahl"
#define LT_MENU_NEW_PrimaryOrder1 "Auto"
#define LT_MENU_NEW_PrimaryOrder2 "Manuell"

#define LT_MENU_NEW_SecondaryOrder0 "Sekundärwaffenauswahl"
#define LT_MENU_NEW_SecondaryOrder1 "Auto"
#define LT_MENU_NEW_SecondaryOrder2 "Manuell"

#define LT_MENU_NEW_SecondaryWeaponKeys0 "Sekundärwaffe"
#define LT_MENU_NEW_SecondaryWeaponKeys1 "Sekundärwaffe"
#define LT_MENU_NEW_SecondaryWeaponKeys2 "Mine abwerfen"
#define LT_MENU_NEW_SecondaryWeaponKeys3 "Mug-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys4 "Solaris-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys5 "Scatter-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys6 "Gravgon-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys7 "MRW"
#define LT_MENU_NEW_SecondaryWeaponKeys8 "Titan-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys9 "Schwebemine"
#define LT_MENU_NEW_SecondaryWeaponKeys10 "Raketenmine"
#define LT_MENU_NEW_SecondaryWeaponKeys11 "Quantummine"
#define LT_MENU_NEW_SecondaryWeaponKeys12 "Nächste Waffe"
#define LT_MENU_NEW_SecondaryWeaponKeys13 "Vorige Waffe"
#define LT_MENU_NEW_SecondaryWeaponKeys14 "Wfe wegwerfen"
#define LT_MENU_NEW_SecondaryWeaponKeys15 "Sekundärwaffe"
#define LT_MENU_NEW_SecondaryWeaponKeys16 "Mine abwerfen"
#define LT_MENU_NEW_SecondaryWeaponKeys17 "Mug-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys18 "Solaris-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys19 "Scatter-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys20 "Gravgon-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys21 "MRW"
#define LT_MENU_NEW_SecondaryWeaponKeys22 "Titan-Rakete"
#define LT_MENU_NEW_SecondaryWeaponKeys23 "Schwebemine"
#define LT_MENU_NEW_SecondaryWeaponKeys24 "Raketenmine"
#define LT_MENU_NEW_SecondaryWeaponKeys25 "Quantummine"
#define LT_MENU_NEW_SecondaryWeaponKeys26 "Nächste Waffe"
#define LT_MENU_NEW_SecondaryWeaponKeys27 "Vorige Waffe"
#define LT_MENU_NEW_SecondaryWeaponKeys28 "Wfe wegwerfen"

#define LT_MENU_NEW_PrimaryWeaponKeys0 "Primärwaffe"
#define LT_MENU_NEW_PrimaryWeaponKeys1 "Primärwaffe"
#define LT_MENU_NEW_PrimaryWeaponKeys2 "Pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys3 "Trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys4 "Pyrolite"
#define LT_MENU_NEW_PrimaryWeaponKeys5 "Transpulse"
#define LT_MENU_NEW_PrimaryWeaponKeys6 "Suss-Kanone"
#define LT_MENU_NEW_PrimaryWeaponKeys7 "Laser"
#define LT_MENU_NEW_PrimaryWeaponKeys8 "Nächste Waffe"
#define LT_MENU_NEW_PrimaryWeaponKeys9 "Vorige Waffe"
#define LT_MENU_NEW_PrimaryWeaponKeys10 "Wfe wegwerfen"
#define LT_MENU_NEW_PrimaryWeaponKeys11 "Nchrt senden"
#define LT_MENU_NEW_PrimaryWeaponKeys12 "Primärwaffe"
#define LT_MENU_NEW_PrimaryWeaponKeys13 "Pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys14 "Trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys15 "Suss-Kanone"
#define LT_MENU_NEW_PrimaryWeaponKeys16 "Pyrolite"
#define LT_MENU_NEW_PrimaryWeaponKeys17 "Transpulse"
#define LT_MENU_NEW_PrimaryWeaponKeys18 "Laser"
#define LT_MENU_NEW_PrimaryWeaponKeys19 "Nächste Waffe"
#define LT_MENU_NEW_PrimaryWeaponKeys20 "Vorige Waffe"
#define LT_MENU_NEW_PrimaryWeaponKeys21 "Wfe wegwerfen"

#define LT_MENU_NEW_Weapons0 "Waffen"
#define LT_MENU_NEW_Weapons1 "Primärwaffentasten"
#define LT_MENU_NEW_Weapons2 "Sekundärwaffentasten"
#define LT_MENU_NEW_Weapons3 "Primärwaffeneinstellungen"
#define LT_MENU_NEW_Weapons4 "Sekundärwaffeneinstellungen"

#define LT_MENU_NEW_ConfigureKeyboard0 "Bewegungssteuerung"
#define LT_MENU_NEW_ConfigureKeyboard1 "links drehen"
#define LT_MENU_NEW_ConfigureKeyboard2 "rechts drehen"
#define LT_MENU_NEW_ConfigureKeyboard3  "oben drehen"
#define LT_MENU_NEW_ConfigureKeyboard4 "unten drehen"
#define LT_MENU_NEW_ConfigureKeyboard5 "links gleiten"
#define LT_MENU_NEW_ConfigureKeyboard6 "rechts gleiten"
#define LT_MENU_NEW_ConfigureKeyboard7 "oben gleiten"
#define LT_MENU_NEW_ConfigureKeyboard8 "unten gleiten"
#define LT_MENU_NEW_ConfigureKeyboard9 "links rollen"
#define LT_MENU_NEW_ConfigureKeyboard10 "rechts rollen"
#define LT_MENU_NEW_ConfigureKeyboard11 "Gleit-Modus"
#define LT_MENU_NEW_ConfigureKeyboard12 "Roll-Modus"
#define LT_MENU_NEW_ConfigureKeyboard13 "Vorwärts"
#define LT_MENU_NEW_ConfigureKeyboard14 "Rückwärts"
#define LT_MENU_NEW_ConfigureKeyboard15 "Nitro"
#define LT_MENU_NEW_ConfigureKeyboard16 "Schneller fahren"
#define LT_MENU_NEW_ConfigureKeyboard17 "Langsamer fahren"
#define LT_MENU_NEW_ConfigureKeyboard18 "links drehen:"
#define LT_MENU_NEW_ConfigureKeyboard19 "rechts drehen:"
#define LT_MENU_NEW_ConfigureKeyboard20 "oben drehen:"
#define LT_MENU_NEW_ConfigureKeyboard21 "unten drehen:"
#define LT_MENU_NEW_ConfigureKeyboard22 "links gleiten:"
#define LT_MENU_NEW_ConfigureKeyboard23 "rechts gleiten:"
#define LT_MENU_NEW_ConfigureKeyboard24 "oben gleiten"
#define LT_MENU_NEW_ConfigureKeyboard25 "unten gleiten:"
#define LT_MENU_NEW_ConfigureKeyboard26 "links rollen:"
#define LT_MENU_NEW_ConfigureKeyboard27 "rechts rollen:"
#define LT_MENU_NEW_ConfigureKeyboard28 "Gleit-Modus:"
#define LT_MENU_NEW_ConfigureKeyboard29 "Roll-Modus:"
#define LT_MENU_NEW_ConfigureKeyboard30 "Vorwärts:"
#define LT_MENU_NEW_ConfigureKeyboard31 "Rückwärts:"
#define LT_MENU_NEW_ConfigureKeyboard32 "Nitro:"
#define LT_MENU_NEW_ConfigureKeyboard33 "Schneller fahren:"
#define LT_MENU_NEW_ConfigureKeyboard34 "Langsamer fahren:"
#define LT_MENU_NEW_ConfigureKeyboard35 "Nchrt senden:"

#define LT_MENU_NEW_ConfigJoyAxis0 "Achsen-Setup"
#define LT_MENU_NEW_ConfigJoyAxis1 "Achse wählen:"
#define LT_MENU_NEW_ConfigJoyAxis2 "Aktion wählen:"
#define LT_MENU_NEW_ConfigJoyAxis3 "Achse umkehren"
#define LT_MENU_NEW_ConfigJoyAxis4 "Empfindlichkeit"
#define LT_MENU_NEW_ConfigJoyAxis5 "Toter Winkel"
#define LT_MENU_NEW_ConfigJoyAxis6 "Feinsteuerung"
#define LT_MENU_NEW_ConfigJoyAxis7 "Test:"

#define LT_MENU_NEW_SetupJoystick20 "Joystick-Setup"
#define LT_MENU_NEW_SetupJoystick21 "Tasten konfigurieren"
#define LT_MENU_NEW_SetupJoystick22 "Achsen konfigurieren"

#define LT_MENU_NEW_SetupJoystick0 "Joystick wählen"
#define LT_MENU_NEW_SetupJoystick1 "Joystick-Liste"

#define LT_AxisScreenItem "Achsen konfigurieren"

#define LT_MENU_NEW_SetupMouse0 "X-Empfindlichkeit"
#define LT_MENU_NEW_SetupMouse1 "Y-Empfindlichkeit"
#define LT_MENU_NEW_SetupMouse2 "X umkehren"
#define LT_MENU_NEW_SetupMouse3 "Y umkehren"

#define LT_MENU_NEW_Controls0 "Steuerung"
#define LT_MENU_NEW_Controls1 "Maus konfigurieren"
#define LT_MENU_NEW_Controls2 "Joystick konfigurieren"
#define LT_MENU_NEW_Controls3 "Tasten und Knöpfe konfigurieren"
#define LT_MENU_NEW_Controls4 "Auto-Ausrichtung"
#define LT_MENU_NEW_Controls5 "Standardeinstellungen"
#define LT_MENU_NEW_Controls6 "Zurück"

#define LT_MENU_NEW_Lights0 "LICHTER"
#define LT_MENU_NEW_Lights1 "Primärlichter"
#define LT_MENU_NEW_Lights2 "Sekundärlichter"
#define LT_MENU_NEW_Lights3 "Pickup-Lichter"
#define LT_MENU_NEW_Lights4 "Zurück"

#define LT_MENU_NEW_DetailLevels0 "DETAILSTUFE"
#define LT_MENU_NEW_DetailLevels1 "Bilinearer Filter"
#define LT_MENU_NEW_DetailLevels2 "Perspektivenkorrektur"
#define LT_MENU_NEW_DetailLevels3 "lens flare effekt"
#define LT_MENU_NEW_DetailLevels4 "Team-Info"
#define LT_MENU_NEW_DetailLevels5 "Detail-Automatik"
#define LT_MENU_NEW_DetailLevels6 "Rauchspuren"
#define LT_MENU_NEW_DetailLevels7 "Bike-Details"
#define LT_MENU_NEW_DetailLevels8 "Wasser-Details"
#define LT_MENU_NEW_DetailLevels9 "Brutalität"
#define LT_MENU_NEW_DetailLevels10 "Primärwaffenlichter"
#define LT_MENU_NEW_DetailLevels11 "Sekundärwaffenlichter"
#define LT_MENU_NEW_DetailLevels12 "Pickup-Lichter"
#define LT_MENU_NEW_DetailLevels13 "Lichter..."
#define LT_MENU_NEW_DetailLevels14 "Zusatz-Info zeigen "
#define LT_MENU_NEW_DetailLevels15 "Abschüsse zeigen"
#define LT_MENU_NEW_DetailLevels16 "Zurück"

#define LT_MENU_NEW_ScreenRes0 "Auswahl:"
#define LT_MENU_NEW_ScreenRes1 "Zurück mit Escape"

#define LT_MENU_NEW_TextureFormat0 "Auswahl:"
#define LT_MENU_NEW_TextureFormat1 "Zurück mit Escape"

#define LT_MENU_NEW_Visuals0 "optik"
#define LT_MENU_NEW_Visuals1 "Detailstufe ändern"
#define LT_MENU_NEW_Visuals2 "Auflösung ändern"
#define LT_MENU_NEW_Visuals3 "Texturformate wählen"
#define LT_MENU_NEW_Visuals4 "gamma"
#define LT_MENU_NEW_Visuals5 "Zurück"

#define LT_MENU_NEW_LobbyWaitingForHost0 "Host wählt Spieltyp, bitte warten"
#define LT_MENU_NEW_LobbyWaitingForHost1 "Abbrechen"

#define LT_MENU_NEW_JoinWaitingToStart0 "Warten auf Host..."
#define LT_MENU_NEW_JoinWaitingToStart1 "Spielerzahl"
#define LT_MENU_NEW_JoinWaitingToStart2 "Nch:"

#define LT_MENU_NEW_GetTeamPlayers0 "Warten auf Host..."
#define LT_MENU_NEW_GetTeamPlayers1 "Spielerzahl"
#define LT_MENU_NEW_GetTeamPlayers2 "Nch:"

#define LT_MENU_NEW_ChooseSessionToJoin0 "Spiel wählen"

#define LT_MENU_NEW_ChooseConnectionToJoin0 "Start"
#define LT_MENU_NEW_ChooseConnectionToJoin1 "Verbindungsart wählen:"
#define LT_MENU_NEW_ChooseConnectionToJoin2 "TCP adresse:"

#define LT_MENU_NEW_ChangeBike0 "Geschw."
#define LT_MENU_NEW_ChangeBike1 "Beschl."
#define LT_MENU_NEW_ChangeBike2 "kontr."
#define LT_MENU_NEW_ChangeBike3 "Schild"
#define LT_MENU_NEW_ChangeBike4 "Panzer."

#define LT_MENU_NEW_ChoosePlayer0 "Spieler wählen"
#define LT_MENU_NEW_ChoosePlayer1 "Liste..."

#define LT_MENU_NEW_NewPlayer0 "Spielernamen eingeben"

#define LT_MENU_NEW_ChangePlayerName0 "Neuen Namen eingeben"

#define LT_MENU_NEW_SelectBiker0 "Spieler wählen"
#define LT_MENU_NEW_SelectBiker1 "Neuer Spieler"
#define LT_MENU_NEW_SelectBiker2 "Spieler umbenennen"
#define LT_MENU_NEW_SelectBiker3 "Bike wechseln"
#define LT_MENU_NEW_SelectBiker4 "Stimme wechseln"
#define LT_MENU_NEW_SelectBiker5 "Beenden"

#define LT_MENU_NEW_DemoPlayBack0 "Demo abspielen"
#define LT_MENU_NEW_DemoPlayBack1 "Start"
#define LT_MENU_NEW_DemoPlayBack2 "geschwind."
#define LT_MENU_NEW_DemoPlayBack3 "Spieler Nr."
#define LT_MENU_NEW_DemoPlayBack4 "Demo wählen"

#define LT_MENU_LoadSavedGame0 "Spiel laden"
#define LT_MENU_LoadSavedGame1 "Auswahl:"

#define LT_MENU_NEW_Sound0 "Sound"
#define LT_MENU_NEW_Sound1 "Sound-Optionen"
#define LT_MENU_NEW_Sound2 "SFX-Lautstärke"
#define LT_MENU_NEW_Sound3 "CD-musik"
#define LT_MENU_NEW_Sound4 "Bike-Motoren"
#define LT_MENU_NEW_Sound5 "Dialogoptionen"
#define LT_MENU_NEW_Sound6 "Biker-Dialoge"
#define LT_MENU_NEW_Sound7 "Computerstimme"

#define LT_MENU_NEW_InGameSound0 "Sound"
#define LT_MENU_NEW_InGameSound1 "SFX-Lautstärke"
#define LT_MENU_NEW_InGameSound2 "CD-Ton        "
#define LT_MENU_NEW_InGameSound3 "Bike-Motoren  "
#define LT_MENU_NEW_InGameSound4 "Biker-Lautst. "
#define LT_MENU_NEW_InGameSound5 "Computerstimme"

#define LT_MENU_NEW_DemoCleaning0 "Demo löschen"
#define LT_MENU_NEW_DemoCleaning1 "Start"
#define LT_MENU_NEW_DemoCleaning2 "Demo wählen"

#define LT_MENU_NEW_RestoreGame0 "Spiel laden"
#define LT_MENU_NEW_RestoreGame1 "Demo abspielen"
#define LT_MENU_NEW_RestoreGame2 "Demo löschen"
#define LT_MENU_NEW_RestoreGame3 "Spiel laden"

#define LT_MENU_NEW_Options0 "Optionen"
#define LT_MENU_NEW_Options1 "Sound"
#define LT_MENU_NEW_Options2 "Optik"
#define LT_MENU_NEW_Options3 "Zurück"

#define LT_MENU_NEW_Setup0 "Biker einstellen"
#define LT_MENU_NEW_Setup1 "Bike wählen"
#define LT_MENU_NEW_Setup2 "Steuerung"
#define LT_MENU_NEW_Setup3 "Waffen"
#define LT_MENU_NEW_Setup4 "Zurück"

#define LT_MENU_NEW_Battle0 "Multiplayer"
#define LT_MENU_NEW_Battle1 "Neues Spiel"
#define LT_MENU_NEW_Battle2 "Spiel beitreten"
#define LT_MENU_NEW_Battle3 "Zurück"
#define LT_MENU_NEW_Battle4 "Server"

#define LT_MENU_NEW_CoOp0 "Co-Op"
#define LT_MENU_NEW_CoOp1 "Spiel beitreten"
#define LT_MENU_NEW_CoOp2 "Netzwerk-Setup"
#define LT_MENU_NEW_CoOp3 "Modem/Seriell"
#define LT_MENU_NEW_CoOp4 "Beenden"

#define LT_MENU_NEW_MissionMenu0 "Einzelspieler"
#define LT_MENU_NEW_MissionMenu1 "Spiel starten"
#define LT_MENU_NEW_MissionMenu2 "Zurück"

#define LT_MENU_NEW_Start0 "Einzelspieler"
#define LT_MENU_NEW_Start1 "Einzelspieler"
#define LT_MENU_NEW_Start2 "Multiplayer"
#define LT_MENU_NEW_Start3 "Biker einstellen"
#define LT_MENU_NEW_Start4 "Demo abspielen"
#define LT_MENU_NEW_Start5 "Spiel laden"
#define LT_MENU_NEW_Start6 "Optionen"
#define LT_MENU_NEW_Start7 "verlassen"

#define LT_MENU_QuickTextSend0 "Nachricht: "

#define LT_MENU_QuickTextSendWhisper0 "Flüsternachricht: "
									  
#define LT_MENU_EditMacro10 "Nachricht 1 ändern"
#define LT_MENU_EditMacro11 "Nachricht 1 eingeben "

#define LT_MENU_EditMacro20 "Nachricht 2 ändern"
#define LT_MENU_EditMacro21 "Nachricht 2 eingeben "

#define LT_MENU_EditMacro30 "Nachricht 3 ändern"
#define LT_MENU_EditMacro31 "Nachricht 3 eingeben "

#define LT_MENU_NEW_Team0 "Teams wählen"
#define LT_MENU_NEW_Team1 "Rot"
#define LT_MENU_NEW_Team2 "Grün"
#define LT_MENU_NEW_Team3 "Blau"
#define LT_MENU_NEW_Team4 "Gelb"
#define LT_MENU_NEW_Team5 "Rot"
#define LT_MENU_NEW_Team6 "Grün"
#define LT_MENU_NEW_Team7 "Blau"
#define LT_MENU_NEW_Team8 "Gelb"
#define LT_MENU_NEW_Team9 "Warten auf Team-Wahl"
#define LT_MENU_NEW_Team10 "Nch:"

#define LT_MENU_NEW_WatchTeamSelect0 "Teams wählen"
#define LT_MENU_NEW_WatchTeamSelect1 "Rot"
#define LT_MENU_NEW_WatchTeamSelect2 "Grün"
#define LT_MENU_NEW_WatchTeamSelect3 "Blau"
#define LT_MENU_NEW_WatchTeamSelect4 "Gelb"
#define LT_MENU_NEW_WatchTeamSelect5 "Rot"
#define LT_MENU_NEW_WatchTeamSelect6 "Grün"
#define LT_MENU_NEW_WatchTeamSelect7 "Blau"
#define LT_MENU_NEW_WatchTeamSelect8 "Gelb"
#define LT_MENU_NEW_WatchTeamSelect9 "Warten auf Team-Wahl"
#define LT_MENU_NEW_WatchTeamSelect10 "Nch:"

#define LT_MENU_NEW_ChooseTeamForExistingGame0 "Teams wählen"
#define LT_MENU_NEW_ChooseTeamForExistingGame1 "Rot"
#define LT_MENU_NEW_ChooseTeamForExistingGame2 "Grün"
#define LT_MENU_NEW_ChooseTeamForExistingGame3 "Blau"
#define LT_MENU_NEW_ChooseTeamForExistingGame4 "Gelb"
#define LT_MENU_NEW_ChooseTeamForExistingGame5 "Rot"
#define LT_MENU_NEW_ChooseTeamForExistingGame6 "Grün"
#define LT_MENU_NEW_ChooseTeamForExistingGame7 "Blau"
#define LT_MENU_NEW_ChooseTeamForExistingGame8 "Gelb"
#define LT_MENU_NEW_ChooseTeamForExistingGame9 "Nch:"

#define LT_MENU_LevelSelect0 "Level-Auswahl"
#define LT_MENU_LevelSelect1 "Möglichkeit zum Wechseln "
#define LT_MENU_LevelSelect2 "Level..."

#define LT_MENU_SaveGame0 "Spiel speichern"
#define LT_MENU_SaveGame1 "Auswahl:"

#define LT_MENU_Keyboard0 "Steuerung konfigurieren"
#define LT_MENU_Keyboard1 "links drehen"
#define LT_MENU_Keyboard2 "rechts drehen"
#define LT_MENU_Keyboard3 "oben drehen"
#define LT_MENU_Keyboard4 "unten drehen"
#define LT_MENU_Keyboard5 "links drehen"
#define LT_MENU_Keyboard6 "rechts drehen"
#define LT_MENU_Keyboard7 "oben gleiten"
#define LT_MENU_Keyboard8 "unten gleiten"
#define LT_MENU_Keyboard9 "links rollen"
#define LT_MENU_Keyboard10 "rechts rollen"
#define LT_MENU_Keyboard11 "Gleit-Modus"
#define LT_MENU_Keyboard12 "Roll-Modus"
#define LT_MENU_Keyboard13 "Vorwärts"
#define LT_MENU_Keyboard14 "Rückwärts"
#define LT_MENU_Keyboard15 "Nitro"
#define LT_MENU_Keyboard16 "Beschleunigen"
#define LT_MENU_Keyboard17 "Abbremsen"
#define LT_MENU_Keyboard18 "Prim. feuern"
#define LT_MENU_Keyboard19 "Sek. feuern"
#define LT_MENU_Keyboard20 "Mine abwerfen"
#define LT_MENU_Keyboard21 "Prim. wegwerfen"
#define LT_MENU_Keyboard22 "Sek. wegwerfen"
#define LT_MENU_Keyboard23 "Schild wegwerfen"
#define LT_MENU_Keyboard24 "Munition wegwerfen"
#define LT_MENU_Keyboard25 "Pulsar"
#define LT_MENU_Keyboard26 "Trojax"
#define LT_MENU_Keyboard27 "Pyrolite"
#define LT_MENU_Keyboard28 "Transpulse"
#define LT_MENU_Keyboard29 "Suss-Kanone"
#define LT_MENU_Keyboard30 "Beamlaser"
#define LT_MENU_Keyboard31 "Nächste Prim"
#define LT_MENU_Keyboard32 "Vorige Prim"
#define LT_MENU_Keyboard33 "Nächste Sek"
#define LT_MENU_Keyboard34 "Vorige Sek"
#define LT_MENU_Keyboard35 "Nchrt senden"
#define LT_MENU_Keyboard36 "Provokation"
#define LT_MENU_Keyboard37 "Mug-Rakete"
#define LT_MENU_Keyboard38 "Solaris"
#define LT_MENU_Keyboard39 "Scatter"
#define LT_MENU_Keyboard40 "Gravgon"
#define LT_MENU_Keyboard41 "MRW"
#define LT_MENU_Keyboard42 "TitanStar"
#define LT_MENU_Keyboard43 "Schwebemine"
#define LT_MENU_Keyboard44 "Raketenmine"
#define LT_MENU_Keyboard45 "Quantummine"

#define LT_MENU_Feedback_Advanced0 "Feedback-Einstellung"
#define LT_MENU_Feedback_Advanced1 "Primär-Feedback   "
#define LT_MENU_Feedback_Advanced2 "Primärstärke   "
#define LT_MENU_Feedback_Advanced3 "Sekundär-Feedback "
#define LT_MENU_Feedback_Advanced4 "Sekundärstärke "
#define LT_MENU_Feedback_Advanced5 "Aufprall-Feedback    "
#define LT_MENU_Feedback_Advanced6 "Aufprallstärke    "
#define LT_MENU_Feedback_Advanced7 "Motoren-Feedback    "
#define LT_MENU_Feedback_Advanced8 "Motorenstärke    "
#define LT_MENU_Feedback_Advanced9 "Stossdämpfer-Feedback    "
#define LT_MENU_Feedback_Advanced10 "Stossdämpferstärke    "
#define LT_MENU_Feedback_Advanced11 "Trägheits-Feedback   "
#define LT_MENU_Feedback_Advanced12 "Trägheitsstärke   "

#define LT_MENU_Feedback0 "Feedback"
#define LT_MENU_Feedback1 "Feedback     "
#define LT_MENU_Feedback2 "Feedback-Stärke"
#define LT_MENU_Feedback3 "X-Achse "
#define LT_MENU_Feedback4 "Y-Achse "
#define LT_MENU_Feedback5 "X-Achse "
#define LT_MENU_Feedback6 "umkehren "
#define LT_MENU_Feedback7 "Y-Achse "
#define LT_MENU_Feedback8 "umkehren "
#define LT_MENU_Feedback9 "Weitere Optionen..."

#define LT_MENU_Controls0 "Bike-Steuerung"
#define LT_MENU_Controls1 "Steuerung konfigurieren"
#define LT_MENU_Controls2 "Maus              "
#define LT_MENU_Controls3 "Joystick          "
#define LT_MENU_Controls4 "Autom. Ausrichtung"
#define LT_MENU_Controls5 "X umkehren        "
#define LT_MENU_Controls6 "Y umkehren        "
#define LT_MENU_Controls7 "X-Empfindlichkeit "
#define LT_MENU_Controls8 "Y-Empfindlichkeit "
#define LT_MENU_Controls9 "Feedback..."

#define LT_MENU_Detail0 "Detailstufe"
#define LT_MENU_Detail1 "Bilinearer Filter  "
#define LT_MENU_Detail2 "Perspektivkorrektur"
#define LT_MENU_Detail3 "lens flare effekt  "
#define LT_MENU_Detail4 "Team-Info          "
#define LT_MENU_Detail5 "Primärwaffenlichter"
#define LT_MENU_Detail6 "Sek-Waffenlichter  "
#define LT_MENU_Detail7 "Pickup-Lichter     "
#define LT_MENU_Detail8 "Mono-Beleuchtung   "
#define LT_MENU_Detail9 "Rauchspurendetails "
#define LT_MENU_Detail10 "autom. Details     "
#define LT_MENU_Detail11 "Bike-Details       "
#define LT_MENU_Detail12 "Wasser-Details     "
#define LT_MENU_Detail13 "Kontrast              "
#define LT_MENU_Detail14 "Brutalität         "

#define LT_MENU_SelectBike0 "Bike wählen"
#define LT_MENU_SelectBike1 "Auswahl:"

#define LT_MENU_SelectBikeComputer0 "Computerstimme wählen"
#define LT_MENU_SelectBikeComputer1 "Auswahl:"

#define LT_MENU_NEW_ChangeBikeComputer0 "Computerstimme wählen"
#define LT_MENU_NEW_ChangeBikeComputer1 "Computerstimme wählen..."
#define LT_MENU_NEW_ChangeBikeComputer2 "Liste..."
					 
#define LT_MENU_SelectScreenMode0 "auflösung wählen"
#define LT_MENU_SelectScreenMode1 "Auswahl:"

#define LT_MENU_SelectTextureFormat0 "Texturen wählen"
#define LT_MENU_SelectTextureFormat1 "Auswahl:"

#define LT_MENU_Visuals0 "Optik"
#define LT_MENU_Visuals1 "auflösung wählen"
#define LT_MENU_Visuals2 "Texturen wählen"
#define LT_MENU_Visuals3 "Vollbildschirm ein/aus"

#define LT_MENU_Options0 "Optionen"
#define LT_MENU_Options1 "Optik"
#define LT_MENU_Options2 "Sound-FX und Musik"
#define LT_MENU_Options3 "Detailstufe"
#define LT_MENU_Options4 "Bildrate zeigen "
#define LT_MENU_Options5 "Pakete pro Sekunde "
#define LT_MENU_Options6 "Ping zeigen"
#define LT_MENU_Options7 "Update (sek)"
#define LT_MENU_Options8 "Zusatz-Info zeigen "
#define LT_MENU_Options9 "Abschüsse zeigen"
#define LT_MENU_Options10 "Standardeinstellungen"

#define LT_MENU_SelfPlayOptions0 "Optionen"
#define LT_MENU_SelfPlayOptions1 "auflösung wählen"
#define LT_MENU_SelfPlayOptions2 "Texturen wählen"
#define LT_MENU_SelfPlayOptions3 "Detailstufe"
#define LT_MENU_SelfPlayOptions4 "Spielernamen zeigen "
#define LT_MENU_SelfPlayOptions5 "Bildrate zeigen "

#define LT_MENU_DemoPlaying0 "Demo-Wiedergabe"
#define LT_MENU_DemoPlaying1 "Demo-Pause"
#define LT_MENU_DemoPlaying2 "Wiederholungsgeschw."
#define LT_MENU_DemoPlaying3 "Spieler beobachten"
#define LT_MENU_DemoPlaying4 "Optionen"
#define LT_MENU_DemoPlaying5 "Zum Hauptmenü"
#define LT_MENU_DemoPlaying6 "3dfx-Demo holen"
#define LT_MENU_DemoPlaying7 "Wiederholungsgeschw."
#define LT_MENU_DemoPlaying8 "Spieler beobachten"
#define LT_MENU_DemoPlaying9 "Optionen"
#define LT_MENU_DemoPlaying10 "Debugging"
#define LT_MENU_DemoPlaying11 "Zum Titelbildschirm"
#define LT_MENU_DemoPlaying12 "Server-Modus"

#define LT_MENU_DemoPlayBack0 "Demo-Wiederholung"
#define LT_MENU_DemoPlayBack1 "Start"
#define LT_MENU_DemoPlayBack2 "Wiederholungsgeschw."
#define LT_MENU_DemoPlayBack3 "Spieler beobachten"
#define LT_MENU_DemoPlayBack4 "Auswahl:"

#define LT_MENU_DemoCleaning0 "Demo löschen"
#define LT_MENU_DemoCleaning1 "Start"
#define LT_MENU_DemoCleaning2 "Output-Name  "
#define LT_MENU_DemoCleaning3 "Auswahl:"

#define LT_MENU_SetUpBiker0 "Biker einstellen"
#define LT_MENU_SetUpBiker1 "Neuen Biker erstellen "
#define LT_MENU_SetUpBiker2 "Bike-Steuerung"
#define LT_MENU_SetUpBiker3 "Bike wählen"
#define LT_MENU_SetUpBiker4 "Computerstimme wählen"
#define LT_MENU_SetUpBiker5 "Auswahl:"

#define LT_MENU_Save0 "Speichermenü"
#define LT_MENU_Save1 "Pickups speichern"

#define LT_MENU_InGame0 "Forsaken"
#define LT_MENU_InGame1 "Biker einstellen "
#define LT_MENU_InGame2 "Vollbildschirm ein/aus"
#define LT_MENU_InGame3 "Spiel laden"
#define LT_MENU_InGame4 "Spiel speichern"
#define LT_MENU_InGame5 "Optionen"
#define LT_MENU_InGame6 "Levelauswahl"
#define LT_MENU_InGame7 "Level beenden und Statistik zeigen"
#define LT_MENU_InGame8 "Zum Hauptmenü"
#define LT_MENU_InGame9 "Ping zeigen"
#define LT_MENU_InGame10 "Update (sek)"
#define LT_MENU_InGame11 "Debugging"
#define LT_MENU_InGame12 "Server-Modus"
#define LT_MENU_InGame13 "Wireframe-Modus"
#define LT_MENU_InGame14 "Speichermenü"
#define LT_MENU_InGame15 "Debug-Menü"
#define LT_MENU_InGame16 "IP "
#define LT_MENU_InGame17 "Pakete pro Sekunde "
#define LT_MENU_InGame18 "Biker einstellen "
#define LT_MENU_InGame19 "Spiel laden"
#define LT_MENU_InGame20 "Spiel speichern"
#define LT_MENU_InGame21 "Optionen"
#define LT_MENU_InGame22 "Zum Hauptmenü"
#define LT_MENU_InGame23 "Debugging"

#define LT_MENU_Help0 "Spiel-Hilfe"
#define LT_MENU_Help1 "Menü ein/aus"
#define LT_MENU_Help2 "Hilfeschirm ein/aus" 
#define LT_MENU_Help3 "Fenster vergrössern" 
#define LT_MENU_Help4 "Fenster verkleinern" 
#define LT_MENU_Help5 "Tafeltext ein/aus" 
#define LT_MENU_Help6 "Fernkamera ein/aus" 
#define LT_MENU_Help7 "Rückkamera ein/aus" 
#define LT_MENU_Help8 "Raketenkamera ein/aus" 
#define LT_MENU_Help9 "Spielernamen ein/aus"
#define LT_MENU_Help10 "Zurück zum Spiel"

// note to translator: the ~ character in the next section represents a line break

#define LT_BorgBikerText "LOKASENNA ARBEITET FÜR PRO:BORG, EINEN GEHEIMBUND, DER VON DER IDEE DER WEITERENTWICKLUNG DURCH SYMBIOTISCHE INTEGRATION VON MENSCH UND MASCHINE BESESSEN IST.~WER NICHT MIT DER PRO:BORG-DOKTRIN EINVERSTANDEN IST, WIRD MIT EFFIZIENTER GNADENLOSIGKEIT BESEITIGT."
#define LT_BeardBikerText "BEARD IST EIN BEINHARTER HEADBANGER. ER RAST AUF EINER BROUGH SUPERIOR 119 DURCHS ALL, STETS BEGLEITET VON SEINEM TOTEN PARTNER 'MAD-DOG MCCOY'. DIE BEIDEN SIND STÄNDIG AUF DER SUCHE NACH HEAVY ACTION!~~LET'S ROCK!!!"
#define LT_LAJayBikerText "L.A. JAY SURFT SCHON EWIG DIE SOLARWELLEN; EIN TYP, DESSEN ÜBERDREHTHEIT NUR VON SEINEM KNALLIGEN HEMD IN DEN SCHATTEN GESTELLT WIRD.~~L.A. IST ZIEMLICH EGAL, WAS ER GERADE MACHT; HAUPTSACHE, ER SIEHT COOL DABEI AUS."
#define LT_ExCopBikerText "EX-COP, DER HÄRTESTE BULLE ALLER ZEITEN, FLOG RAUS, ALS ER BEI EINER DROGENRAZZIA NEUN PUNKS ERSCHOSSEN HATTE. EX-COP BERIEF SICH AUF LATENTE SCHIESSWÜTIGKEIT. ÜBERHAUPT: 'WARUM LEUTE EINSPERREN, WENN MAN SIE GENAUSOGUT WEGPUSTEN KANN?'"
#define LT_TruckerBikerText "JEDER, DER EIN PAAR DER HERUNTER - GEKOMMENEREN INTERSTELLAREN TRUCKSTOPS KENNT, HAT SICHER SCHON VON DIESEM LEGENDÄREN TRUCKER GEHÖRT... REX HARDY. DIE GESCHICHTEN AUS SEINEM GEWALTVOLLEN LEBEN HABEN IHN ZU EINEM GEFÜRCHTETEN UND RESPEKTIERTEN IDOL GEMACHT."
#define LT_FoetoedBikerText "DIESE EKELERREGENDE GENMUTATION, EINGESCHLOSSEN IN EINE GEBÄRMUTTER AUS STAHL UND NUR ALS FOETOID BEKANNT, BRINGT TOD UND VERWÜSTUNG ÜBER ALLE.~~KEIN SCHIMMER VON MORALGEFÜHL HÄLT SIE ZURÜCK."
#define LT_JapBirdBikerText "NIM SOO SUN IST EINE GEWALTTÄTIGE PSYCHOPATHIN - WEN WUNDERT'S DA, DASS SIE SICH DEN SPITZNAMEN 'DIE KLEINE MIT DER KLINGE' VERDIENT HAT. DAS EX-MITGLIED DES BERÜCHTIGTEN XENO-ZIRKUS HANDELT HEUTE MIT ANTIKEN RELIKTEN AUS UNBEWOHNBAREN WELTEN. DIE ERDE IST IHR NÄCHSTES ZIEL..."
#define LT_NuttaBikerText "NUTTA WAR EINMAL EIN BERÜHMTER ARZT UND EHRBARER BÜRGER. DOCH UNTER DIESER FASSADE LAG DER BLANKE WAHNSINN. DER ARZT WURDE SCHLIESSLICH EINGEWIESEN, NACHDEM ER EINEN PATIENTEN MIT DEM HOLZHAMMER IN NARKOSE VERSETZEN WOLLTE! NUN, ER KONNTE FLIEHEN..."
#define LT_SceptreBikerText "OBWOHL ER DURCH EINE GRAUSAME GENKRANKHEIT ENTSTELLT IST, HAT SCEPTRE DEN STATUS DES WAHRHAFT GEFÜRCHTETEN UND VERABSCHEUTEN ERLANGT.~~IN DEN LETZTEN JAHREN HAT ER MEHREREN WELTEN SEINEN EISERNEN WILLEN AUFGEZWUNGEN UND IHRE VERÄNGSTIGTEN BEWOHNER VERSKLAVT." 
#define LT_JoBikerText "ER IST DER ULTIMATIVE COMPUTERFREAK; HALB SORGLOSER HIPPIE, HALB HARDCORE - TECHNIKFANATIKER.~~JO MACHT DIESE ARBEIT NUR AUS EINEM GRUND: SEINER VORLIEBE FÜR CYBER-JUNK, COOLE WAFFEN UND TECHNOLOGIE."
#define LT_SharkBikerText "CUVEL IST EIN TYPISCHER GERISSENER, SKRUPELLOSER, MIESER BETRÜGER... NUR SCHLIMMER. ER WEISS, WO ES GELD ZU HOLEN GIBT, UND WIE MAN ES SICH HOLT.~~WARUM FÜR ETWAS ARBEITEN, DAS MAN STEHLEN KANN?" 
#define LT_HK5BikerText "HK-5 BELEGT EINDRUCKSVOLL, WAS MIT COMPUTERGESTEUERTER KAMPFSCHIFF - TECHNOLOGIE SCHIEFGEHEN KANN. SEIN SILIKONHIRN IST VON GRÖSSENWAHN, GIER UND EINEM HASS AUF ALLES HUMANOIDE LEBEN ZERFRESSEN.~~ER HAT NUR EIN ZIEL: MASSENMORD."
#define LT_NubiaBikerText "NUBIA IST AUF BEWAFFNETEN RAUB UND BEZAHLTEN MORD SPEZIALISIERT.~~SEIT KURZEM VERSUCHT SIE SICH AUCH IN COMPUTERKRIMINALITÄT UND BETRUG. KEINER, DER SICH MIT IHR ANGELEGT HAT, HAT ÜBERLEBT.~~EINE WAHRE HYÄNE VON EINEM WEIB."
#define LT_MophistoBikerText "TTEC IV - DIE NEUESTEN ALLZWECK - KAMPFDROIDEN. IM JAHRE 2112 SOLLTEN ALLE AUFGRUND DEFEKTER STEUERKABEL VERNICHTET WERDEN. MOFISTO WAR EIN TTEC IV. DIE NACHRICHT VON SEINER BEVORSTEHENDEN ABSCHALTUNG GEFIEL SEINEM ÜBERLEBENSCODE GAR NICHT. NIE WAR METALL SO GEFÄHRLICH WIE HEUTE!"
#define LT_CerberoBikerText "EINE MISCHUNG AUS MENSCH UND MASCHINE, DIE DEN ABSCHAUM DES UNIVERSUMS BESEITIGT. EIN HERZ AUS TITAN, TOXIN-RESISTENTE LUNGEN UND I.R.-EMPFINDLICHE AUGEN SIND NUR EIN PAAR DER MODIFIKATIONEN, DIE IHN ZU EINEM KLINISCH KALTEN KILLER GEMACHT HABEN."
#define LT_SleekBikerText "EARL IST DER SCHÄRFSTE FUNK-MASTER DER GALAXIE. ER HAT SICH FÜR DIESEN JOB ENTSCHIEDEN, WEIL ER SCHNELLEN PROFIT ROCH. KEINER HAT DEN MUMM, ES MIT EARL AUFZUNEHMEN, UND DAS WEISS ER. 'HEY BABY, THE MAN'S IN TOWN'."
#define LT_FlygirlBikerText "Man weiss nur wenig über dieses rätselhafte Wesen. Söldner, die ihren Klauen entronnen sind, haben sie 'Flygirl' getauft. Man sagt, sie sei die letzte Überlebende der Erde; eine Erwachsene mit dem Geist eines Kindes, aber voller Bosheit. Selten zu sehen, schwer zu vergessen."


#define LT_ToggleStatusOn "ein"
#define LT_ToggleStatusOff "aus"
#define LT_Undef "n. def."	// ( short for undefined )
#define LT_SelectWhenReady "Wählen, wenn bereit"
#define LT_WaitingForReset "Warten..."

#define LT_PageNo "Seite %d von %d"	// %d = number
#define LT_PageDown	"  [BildAb]=mehr"
#define LT_PageUpDown "  [BildAuf/Ab]=mehr"
#define LT_PageUp "  [BildAuf]=mehr"
#define LT_PressKey "Taste oder Knopf drücken für %s"	// %s will be name of action
#define LT_ViewAlternateKeys "[rechts]=Ansicht anderer Tasten für %s"	// %s = action
#define LT_ViewAlternateKeys2 "[links]=Ansicht anderer Tasten für %s"	// %s = action
#define LT_SelectControl "[oben/unten]=Steuerung wählen" 
#define LT_Cancel "[Esc]=Abbrechen" 
#define LT_Edit "[ENTER]=Ändern, [Entf]=Löschen der Taste %s"	// %s = action
#define LT_Add "[ENTER]=Hinzufügen, [Entf]=Löschen der Taste %s"	// %s = action

#define LT_Unconnected1 " ist nicht verbunden"
#define LT_Unconnected2 " nicht verbunden"
#define LT_AlsoControls "[%s] steuert auch "

#define LT_ToggleOn " EIN"  
#define LT_ToggleOff " AUS"
#define LT_Undef "n. def."	// short for undefined 

#define LT_QuitToLobby "Zur Lobby"   
#define LT_QuitToMainMenu "Zum Hauptmenü"

#define LT_PlayersGame "%ss Spiel"	// %s is player name   
#define LT_PlayersGame2 "%ss Spiel"	// %s is player name

#define LT_SavedGameName "gespeichert am %d-%d-%d um %2d:%02d"	// %d-%d-%d is day-month-year %2d:%02d is time
#define LT_LevelName "Levelname: %s"	// %s is name of level
#define LT_LevelPlayedFor1 "%s spielte %hd min %hd sek"	// %s = player name, %hd = num mins, %hd = num secs  
#define LT_LevelPlayedFor2 "spielte %hd min %hd sek"		// %s = player name, %hd = num mins, %hd = num secs  
#define LT_EnemiesKilled "abschüsse: %hd von %hd"	// %hd = number 

#define LT_NoSavedGamesFound "Keine gespeicherten Spiele gefunden"

#define LT_NoLimit "Kein Limit"
#define LT_OneMinute "1 min"
#define LT_ManyMinutes "%d min"	// %d = num minutes 
#define LT_NoValue "Keine Zahl" 

#define LT_SpaceOrb "Sie müssen Spaceware verwenden, um die Spaceball-Achse einzustellen"

#define LT_NoJoysticks "Keine Joysticks angeschlossen~~(Während des Spiels können Sie keinen Joystick anschliessen)"	// ~~ = newline  

#define LT_OneCrystalFound "%d Kristall gefunden"	// %d is number of crystals
#define LT_CrystalsFound "%d Kristalle gefunden"	// %d is number of crystals

#define	LT_OneSecretFoundOutOf "%d Geheimnis gefunden von %d"
#define	LT_SecretsFoundOutOf "%d Geheimnisse gefunden von %d"

#define LT_OneGoldBarFound "%d Goldbarren gefunden"	// %d is number of gold bars 
#define LT_GoldBarsFound "%d Goldbarren gefunden"	// %d is number of gold bars 

#define LT_OneEnemyKilled "%d Gegner abgeschossen von %d" 
#define LT_EnemysKilled "%d Gegner abgeschossen von %d" 

#define LT_TimeTaken1 "Gestoppte Zeit %d min %d sek" 
#define LT_TimeTaken2 "Gestoppte Zeit %d min %d sek" 
#define LT_TimeTaken3 "Gestoppte Zeit %d min %d sek" 
#define LT_TimeTaken4 "Gestoppte Zeit %d min %d sek"

#define LT_CTF_Normal "Normal"
#define LT_CTF_MustCarry "Zurücktragen"
#define LT_CTF_CanCarry "Aufheben"
#define LT_CTF_OneTouch "Zurück auf Berührung"
#define LT_CTF_NoReturn "Nicht aufheben"
#define LT_CTF_Standard "Standard"

#define LT_BigPacketsSelected "Kurze Pakete automatisch eingeschaltet" 
#define LT_ShortPacketsSelected "Paketgruppen automatisch ausgeschaltet" 

/*********************************************************************

  ADDED SINCE FULL RELEASE

*********************************************************************/
#define LT_MENU_Keyboard1a "scheinwerfer"
#define LT_MENU_Keyboard1b "volle hinteransicht"

#define LT_MENU_InGame1a "server menü"

#define LT_MENU_ServerMenu0 "server optionen"
#define LT_MENU_ServerMenu1 "server rendert"
#define LT_MENU_ServerMenu2 "jetzige spieler"

#define MENU_NEW_CreateGamePseudoHost0 "server verwaltet kollisionen"

#define LT_MENU_NEW_ChooseConnectionToStart1 "drücken sie 'q' zum verlassen"

#define LT_MENU_NEW_MoreMultiplayerOptions21 "anzahl primäre waffen"

#define LT_Extra1 "leere server session - wählen sie, um eine session auf diesem server zu hosten"
#define LT_Extra2 "server session - host wählt spielart"
#define LT_Extra3 "session erstellt %d-%d-%d bei %02d:%02d"
#define LT_Extra4 "level: %s"
#define LT_Extra5 "spieler: %d / %d"
#define LT_Extra6 "spiel: %s%s"
#define LT_Extra7 "pakete: kurz %s, gruppiert %s"
#define LT_Extra8 "verzög. toleranz: %s"
#define LT_Extra9 "server basierendes spiel"
#define LT_Extra10 "partner verletzen %s"
#define LT_Extra11 "abschuss limit %d ( highscore %d )"
#define LT_Extra12 "zeitlimit %d min ( %d übrig )"
#define LT_Extra13 "leuchtende bikes: %s"
#define LT_Extra14 "bike auspuff: %s"


#endif // LOCALTITLE_INCLUDED

 
