
#ifndef LOCALTITLE_INCLUDED
#define LOCALTITLE_INCLUDED

#define LT_MacroText1 "you ugly son of a bitch..." 
#define LT_MacroText2 "Time to die..." 
#define LT_MacroText3 "I will tear your soul apart..."

#define LT_GameCompleteWithoutCrystals "well done. You completed all the levels but you didn't get all the crystals. You'll have to do it all over again if you want to be properly rewarded." 
#define LT_GameCompleteGotAllCrystalsSoFar "well done, you got all the crystals. Take an extra life for the secret level. Find the crystal here for a special award." 
#define LT_GameCompleteWithAllCrystals "well done, you got all the crystals. You get the secret biker."
#define LT_GameCompleteWithAllCrystalsExceptLast "well you got through the secret level, but you didn't get the final crystal. Better luck next time."
#define LT_GameCompleteWithCheating "well, you completed the game but you cheated, didn't you. If you want to see the secret level and have a chance to get a special reward, you'll have to do it properly!"
#define LT_GameCompleteAdditionalLevels "congratulations. You have completed all the currently installed additional levels. Look out for further mission packs!!"

#define LT_MENU_NEW_SpecialMessage0 "ok"

#define LT_MENU_NEW_NumberOfSecretsEnemys0 "ok"

#define LT_MENU_NEW_NumberOfGoldBars0 "ok"

#define LT_MENU_NEW_NumberOfCrystals0 "ok"

#define LT_MENU_NEW_StartSinglePlayer0 "single player game" 
#define LT_MENU_NEW_StartSinglePlayer1 "start" 
#define LT_MENU_NEW_StartSinglePlayer2 "select level" 

#define LT_MENU_NEW_Error0 "ok"

#define LT_MENU_NEW_GeneralLoading0 "loading..."

#define LT_MENU_NEW_HostWaitingToStart0 "waiting to start..." 
#define LT_MENU_NEW_HostWaitingToStart1 "start" 
#define LT_MENU_NEW_HostWaitingToStart2 "IP:" 
#define LT_MENU_NEW_HostWaitingToStart3 "Num of Players" 
#define LT_MENU_NEW_HostWaitingToStart4 "msg:" 

#define LT_MENU_NEW_ValidPickups0 "allowed pickups"
#define LT_MENU_NEW_ValidPickups1 "trojax"
#define LT_MENU_NEW_ValidPickups2 "pyrolite"
#define LT_MENU_NEW_ValidPickups3 "transpulse"
#define LT_MENU_NEW_ValidPickups4 "suss gun"
#define LT_MENU_NEW_ValidPickups5 "laser"
#define LT_MENU_NEW_ValidPickups6 "mug"
#define LT_MENU_NEW_ValidPickups7 "solaris"
#define LT_MENU_NEW_ValidPickups8 "scatter"
#define LT_MENU_NEW_ValidPickups9 "gravgon"
#define LT_MENU_NEW_ValidPickups10 "mfrl"
#define LT_MENU_NEW_ValidPickups11 "titan"
#define LT_MENU_NEW_ValidPickups12 "purge mine"
#define LT_MENU_NEW_ValidPickups13 "pine mine"
#define LT_MENU_NEW_ValidPickups14 "quantum mine"
#define LT_MENU_NEW_ValidPickups15 "chaos shield"
#define LT_MENU_NEW_ValidPickups16 "nitro"
#define LT_MENU_NEW_ValidPickups17 "stealth mantle"
#define LT_MENU_NEW_ValidPickups18 "orbit pulsar"
#define LT_MENU_NEW_ValidPickups19 "golden power pod"
#define LT_MENU_NEW_ValidPickups20 "thief"
#define LT_MENU_NEW_ValidPickups21 "spider mine"
#define LT_MENU_NEW_ValidPickups22 "primary weapons"
#define LT_MENU_NEW_ValidPickups23 "power-ups"
#define LT_MENU_NEW_ValidPickups24 "missiles"
#define LT_MENU_NEW_ValidPickups25 "mines"

#define LT_MENU_NEW_MoreMultiplayerOptions0 "Multiplayer options"
#define LT_MENU_NEW_MoreMultiplayerOptions1 "collision perspective"
#define LT_MENU_NEW_MoreMultiplayerOptions2 "short packets"
#define LT_MENU_NEW_MoreMultiplayerOptions4 "packet rate"
#define LT_MENU_NEW_MoreMultiplayerOptions10 "Bounty bonus" 
#define LT_MENU_NEW_MoreMultiplayerOptions11 "flag capture score" 
#define LT_MENU_NEW_MoreMultiplayerOptions12 "bounty bonus interval" 
#define LT_MENU_NEW_MoreMultiplayerOptions13 "own flag rule" 
#define LT_MENU_NEW_MoreMultiplayerOptions14 "record demo"
#define LT_MENU_NEW_MoreMultiplayerOptions15 "demo name"
#define LT_MENU_NEW_MoreMultiplayerOptions16 "damage done when..."
#define LT_MENU_NEW_MoreMultiplayerOptions17 "i think my shots hit you"
#define LT_MENU_NEW_MoreMultiplayerOptions18 "i think your shots hit me"
#define LT_MENU_NEW_MoreMultiplayerOptions19 "change allowed pickups"
#define LT_MENU_NEW_MoreMultiplayerOptions20 "randomize pickups"
#define LT_MENU_NEW_MoreMultiplayerOptions21 "num primaries"
#define LT_MENU_NEW_MoreMultiplayerOptions22 "next page of pickups"

#define LT_MENU_NEW_CreateGame0 "Create Multiplayer Game"
#define LT_MENU_NEW_CreateGame1 "Start game"
#define LT_MENU_NEW_CreateGame2 "IP:"
#define LT_MENU_NEW_CreateGame3 "session name"
#define LT_MENU_NEW_CreateGame4 "level"
#define LT_MENU_NEW_CreateGame5 "player limit"
#define LT_MENU_NEW_CreateGame6 "score limit"
#define LT_MENU_NEW_CreateGame7 "time limit"
#define LT_MENU_NEW_CreateGame8 "game type"
#define LT_MENU_NEW_CreateGame9 "free for all"
#define LT_MENU_NEW_CreateGame10 "team game"
#define LT_MENU_NEW_CreateGame11 "capture the flag"
#define LT_MENU_NEW_CreateGame12 "flag chase"
#define LT_MENU_NEW_CreateGame13 "bounty hunt"
#define LT_MENU_NEW_CreateGame14 "Team bounty hunt"
#define LT_MENU_NEW_CreateGame16 "more options"

#define LT_MENU_NEW_PrimaryOrder0 "primary weapon selection preferences"
#define LT_MENU_NEW_PrimaryOrder1 "auto"
#define LT_MENU_NEW_PrimaryOrder2 "manual"

#define LT_MENU_NEW_SecondaryOrder0 "secondary weapon selection preferences"
#define LT_MENU_NEW_SecondaryOrder1 "auto"
#define LT_MENU_NEW_SecondaryOrder2 "manual"

#define LT_MENU_NEW_SecondaryWeaponKeys0 "secondary weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys1 "fire secondary"
#define LT_MENU_NEW_SecondaryWeaponKeys2 "drop mine"
#define LT_MENU_NEW_SecondaryWeaponKeys3 "mug missile"
#define LT_MENU_NEW_SecondaryWeaponKeys4 "solaris missile"
#define LT_MENU_NEW_SecondaryWeaponKeys5 "scatter missile"
#define LT_MENU_NEW_SecondaryWeaponKeys6 "gravgon missile"
#define LT_MENU_NEW_SecondaryWeaponKeys7 "mfrl"
#define LT_MENU_NEW_SecondaryWeaponKeys8 "Titan Missile"
#define LT_MENU_NEW_SecondaryWeaponKeys9 "purge mine"
#define LT_MENU_NEW_SecondaryWeaponKeys10 "pine mine"
#define LT_MENU_NEW_SecondaryWeaponKeys11 "quantum mine"
#define LT_MENU_NEW_SecondaryWeaponKeys12 "Next weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys13 "Prev weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys14 "drop weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys15 "fire secondary"
#define LT_MENU_NEW_SecondaryWeaponKeys16 "drop mine"
#define LT_MENU_NEW_SecondaryWeaponKeys17 "mug missile"
#define LT_MENU_NEW_SecondaryWeaponKeys18 "solaris missile"
#define LT_MENU_NEW_SecondaryWeaponKeys19 "scatter missile"
#define LT_MENU_NEW_SecondaryWeaponKeys20 "gravgon missile"
#define LT_MENU_NEW_SecondaryWeaponKeys21 "mfrl"
#define LT_MENU_NEW_SecondaryWeaponKeys22 "Titan Missile"
#define LT_MENU_NEW_SecondaryWeaponKeys23 "purge mine"
#define LT_MENU_NEW_SecondaryWeaponKeys24 "pine mine"
#define LT_MENU_NEW_SecondaryWeaponKeys25 "quantum mine"
#define LT_MENU_NEW_SecondaryWeaponKeys26 "Next weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys27 "Prev weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys28 "drop weapon"
#define LT_MENU_NEW_SecondaryWeaponKeys29 "thief missile"
#define LT_MENU_NEW_SecondaryWeaponKeys30 "spider mine"

#define LT_MENU_NEW_PrimaryWeaponKeys0 "primary weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys1 "fire primary"
#define LT_MENU_NEW_PrimaryWeaponKeys2 "pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys3 "trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys4 "pyrolite"
#define LT_MENU_NEW_PrimaryWeaponKeys5 "transpulse"
#define LT_MENU_NEW_PrimaryWeaponKeys6 "suss gun"
#define LT_MENU_NEW_PrimaryWeaponKeys7 "laser"
#define LT_MENU_NEW_PrimaryWeaponKeys8 "Next weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys9 "Prev weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys10 "drop weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys11 "send msg"
#define LT_MENU_NEW_PrimaryWeaponKeys12 "fire primary"
#define LT_MENU_NEW_PrimaryWeaponKeys13 "pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys14 "trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys15 "suss gun"
#define LT_MENU_NEW_PrimaryWeaponKeys16 "pyrolite"
#define LT_MENU_NEW_PrimaryWeaponKeys17 "transpulse"
#define LT_MENU_NEW_PrimaryWeaponKeys18 "laser"
#define LT_MENU_NEW_PrimaryWeaponKeys19 "Next weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys20 "Prev weapon"
#define LT_MENU_NEW_PrimaryWeaponKeys21 "drop weapon"

#define LT_MENU_NEW_Weapons0 "weapons"
#define LT_MENU_NEW_Weapons1 "primary weapon keys"
#define LT_MENU_NEW_Weapons2 "secondary weapon keys"
#define LT_MENU_NEW_Weapons3 "primary weapon preferences"
#define LT_MENU_NEW_Weapons4 "secondary weapon preferences"

#define LT_MENU_NEW_ConfigureKeyboard0 "movement controls"
#define LT_MENU_NEW_ConfigureKeyboard1 "rotate left"
#define LT_MENU_NEW_ConfigureKeyboard2 "rotate right"
#define LT_MENU_NEW_ConfigureKeyboard3  "rotate up"
#define LT_MENU_NEW_ConfigureKeyboard4 "rotate down"
#define LT_MENU_NEW_ConfigureKeyboard5 "slide left"
#define LT_MENU_NEW_ConfigureKeyboard6 "slide right"
#define LT_MENU_NEW_ConfigureKeyboard7 "slide up"
#define LT_MENU_NEW_ConfigureKeyboard8 "slide down"
#define LT_MENU_NEW_ConfigureKeyboard9 "roll left"
#define LT_MENU_NEW_ConfigureKeyboard10 "roll right"
#define LT_MENU_NEW_ConfigureKeyboard11 "slide mode"
#define LT_MENU_NEW_ConfigureKeyboard12 "roll mode"
#define LT_MENU_NEW_ConfigureKeyboard13 "forward"
#define LT_MENU_NEW_ConfigureKeyboard14 "reverse"
#define LT_MENU_NEW_ConfigureKeyboard15 "nitro"
#define LT_MENU_NEW_ConfigureKeyboard16 "cruise faster"
#define LT_MENU_NEW_ConfigureKeyboard17 "cruise slower"
#define LT_MENU_NEW_ConfigureKeyboard18 "rotate left:"
#define LT_MENU_NEW_ConfigureKeyboard19 "rotate right:"
#define LT_MENU_NEW_ConfigureKeyboard20 "rotate up:"
#define LT_MENU_NEW_ConfigureKeyboard21 "rotate down:"
#define LT_MENU_NEW_ConfigureKeyboard22 "slide left:"
#define LT_MENU_NEW_ConfigureKeyboard23 "slide right:"
#define LT_MENU_NEW_ConfigureKeyboard24 "slide up"
#define LT_MENU_NEW_ConfigureKeyboard25 "slide down:"
#define LT_MENU_NEW_ConfigureKeyboard26 "roll left:"
#define LT_MENU_NEW_ConfigureKeyboard27 "roll right:"
#define LT_MENU_NEW_ConfigureKeyboard28 "slide mode:"
#define LT_MENU_NEW_ConfigureKeyboard29 "roll mode:"
#define LT_MENU_NEW_ConfigureKeyboard30 "forward:"
#define LT_MENU_NEW_ConfigureKeyboard31 "reverse:"
#define LT_MENU_NEW_ConfigureKeyboard32 "nitro:"
#define LT_MENU_NEW_ConfigureKeyboard33 "cruise faster:"
#define LT_MENU_NEW_ConfigureKeyboard34 "cruise slower:"
#define LT_MENU_NEW_ConfigureKeyboard35 "send msg:"

#define LT_MENU_NEW_ConfigJoyAxis0 "setup axis"
#define LT_MENU_NEW_ConfigJoyAxis1 "select axis:"
#define LT_MENU_NEW_ConfigJoyAxis2 "select action:"
#define LT_MENU_NEW_ConfigJoyAxis3 "invert axis"
#define LT_MENU_NEW_ConfigJoyAxis4 "sensitivity"
#define LT_MENU_NEW_ConfigJoyAxis5 "deadzone"
#define LT_MENU_NEW_ConfigJoyAxis6 "fine control"
#define LT_MENU_NEW_ConfigJoyAxis7 "test:"

#define LT_MENU_NEW_SetupJoystick22 "configure Axis"

#define LT_MENU_NEW_SetupJoystick0 "choose joystick"
#define LT_MENU_NEW_SetupJoystick1 "joystick list"

#define LT_AxisScreenItem "configure Axis"

#define LT_MENU_NEW_SetupMouse0 "X sensitivity"
#define LT_MENU_NEW_SetupMouse1 "Y sensitivity"
#define LT_MENU_NEW_SetupMouse2 "invert x"
#define LT_MENU_NEW_SetupMouse3 "invert y"

#define LT_MENU_NEW_Controls0 "controls"
#define LT_MENU_NEW_Controls1 "configure mouse"
#define LT_MENU_NEW_Controls2 "configure joystick"
#define LT_MENU_NEW_Controls3 "configure keys and buttons"
#define LT_MENU_NEW_Controls4 "autoleveling"
#define LT_MENU_NEW_Controls5 "restore defaults"
#define LT_MENU_NEW_Controls6 "back"

#define LT_MENU_NEW_Lights0 "LIGHTS"
#define LT_MENU_NEW_Lights1 "Primary Lights"
#define LT_MENU_NEW_Lights2 "Secondary Lights"
#define LT_MENU_NEW_Lights3 "Pickup Lights"
#define LT_MENU_NEW_Lights4 "Back"

#define LT_MENU_NEW_DetailLevels0 "DETAIL LEVELS"
#define LT_MENU_NEW_DetailLevels1 "in game Bi-Linear"
#define LT_MENU_NEW_DetailLevels2 "Perspective Correct"
#define LT_MENU_NEW_DetailLevels4 "Team Info"
#define LT_MENU_NEW_DetailLevels5 "Auto Detail"
#define LT_MENU_NEW_DetailLevels7 "Bike Detail"
#define LT_MENU_NEW_DetailLevels8 "Water Detail"
#define LT_MENU_NEW_DetailLevels10 "Primary Lights"
#define LT_MENU_NEW_DetailLevels11 "Secondary Lights"
#define LT_MENU_NEW_DetailLevels12 "Pickup Lights"
#define LT_MENU_NEW_DetailLevels13 "Lights..."
#define LT_MENU_NEW_DetailLevels14 "Show Extra Info "
#define LT_MENU_NEW_DetailLevels15 "Show Weapon Kills"
#define LT_MENU_NEW_DetailLevels16 "Back"

#define LT_MENU_NEW_ScreenRes0 "Choose From..."
#define LT_MENU_NEW_ScreenRes1 "press escape to go back"

#define LT_MENU_NEW_TextureFormat0 "Choose From..."
#define LT_MENU_NEW_TextureFormat1 "press escape to go back"

#define LT_MENU_NEW_Visuals0 "Visuals"
#define LT_MENU_NEW_Visuals1 "Change Detail Levels"
#define LT_MENU_NEW_Visuals2 "Change Screen Res"
#define LT_MENU_NEW_Visuals3 "Select Texture Format"
#define LT_MENU_NEW_Visuals4 "gamma"
#define LT_MENU_NEW_Visuals5 "back"

#define LT_MENU_NEW_JoinWaitingToStart0 "waiting for host..."
#define LT_MENU_NEW_JoinWaitingToStart1 "Num of Players"
#define LT_MENU_NEW_JoinWaitingToStart2 "msg:"

#define LT_MENU_NEW_GetTeamPlayers0 "waiting for host..."
#define LT_MENU_NEW_GetTeamPlayers1 "Num of Players"
#define LT_MENU_NEW_GetTeamPlayers2 "msg:"

#define LT_MENU_NEW_ChangeBike0 "speed"
#define LT_MENU_NEW_ChangeBike1 "accel"
#define LT_MENU_NEW_ChangeBike2 "handling"
#define LT_MENU_NEW_ChangeBike3 "shield"
#define LT_MENU_NEW_ChangeBike4 "hull"

#define LT_MENU_NEW_ChoosePlayer0 "Choose Player"
#define LT_MENU_NEW_ChoosePlayer1 "list..."

#define LT_MENU_NEW_NewPlayer0 "Enter Player Name"

#define LT_MENU_NEW_ChangePlayerName0 "Enter new Name"

#define LT_MENU_NEW_SelectBiker0 "Choose Player"
#define LT_MENU_NEW_SelectBiker1 "New Player"
#define LT_MENU_NEW_SelectBiker2 "rename player"
#define LT_MENU_NEW_SelectBiker3 "Change Bike"
#define LT_MENU_NEW_SelectBiker4 "Change Bike computer"
#define LT_MENU_NEW_SelectBiker5 "Exit"

#define LT_MENU_NEW_DemoPlayBack0 "play back demo"
#define LT_MENU_NEW_DemoPlayBack1 "Start"
#define LT_MENU_NEW_DemoPlayBack2 "playback speed"
#define LT_MENU_NEW_DemoPlayBack3 "watch player"
#define LT_MENU_NEW_DemoPlayBack4 "choose demo"

#define LT_MENU_LoadSavedGame0 "Load Saved Game"
#define LT_MENU_LoadSavedGame1 "Choose From..."

#define LT_MENU_NEW_Sound0 "sound"
#define LT_MENU_NEW_Sound1 "sound options"
#define LT_MENU_NEW_Sound2 "sfx volume"
#define LT_MENU_NEW_Sound4 "bike engines"
#define LT_MENU_NEW_Sound5 "speech options"
#define LT_MENU_NEW_Sound6 "biker speech"
#define LT_MENU_NEW_Sound7 "bike computer"
#define LT_MENU_NEW_Sound8 "flag sfx"

#define LT_MENU_NEW_InGameSound0 "sound"
#define LT_MENU_NEW_InGameSound1 "sfx volume    "
#define LT_MENU_NEW_InGameSound3 "bike engines  "
#define LT_MENU_NEW_InGameSound4 "biker volume  "
#define LT_MENU_NEW_InGameSound5 "bike computer "
#define LT_MENU_NEW_InGameSound6 "flag sfx      "

#define LT_MENU_NEW_DemoCleaning0 "clean a demo"
#define LT_MENU_NEW_DemoCleaning1 "Start"
#define LT_MENU_NEW_DemoCleaning2 "choose demo"

#define LT_MENU_NEW_RestoreGame0 "Restore Game"
#define LT_MENU_NEW_RestoreGame1 "Play Demo"
#define LT_MENU_NEW_RestoreGame2 "Clean Demo"
#define LT_MENU_NEW_RestoreGame3 "load game"

#define LT_MENU_NEW_Options0 "Options"
#define LT_MENU_NEW_Options1 "Sound"
#define LT_MENU_NEW_Options2 "Visuals"
#define LT_MENU_NEW_Options3 "back"

#define LT_MENU_NEW_Setup0 "Setup Biker"
#define LT_MENU_NEW_Setup1 "Select Bike"
#define LT_MENU_NEW_Setup2 "Controls"
#define LT_MENU_NEW_Setup3 "Weapons"
#define LT_MENU_NEW_Setup4 "back"

#define LT_MENU_NEW_Battle0 "death match"
#define LT_MENU_NEW_Battle1 "Create Game"
#define LT_MENU_NEW_Battle2 "Join Game"
#define LT_MENU_NEW_Battle3 "back"

#define LT_MENU_NEW_CoOp0 "Co Op"
#define LT_MENU_NEW_CoOp1 "Join Game"
#define LT_MENU_NEW_CoOp2 "Network Setup"
#define LT_MENU_NEW_CoOp3 "Modem/Serial"
#define LT_MENU_NEW_CoOp4 "Exit"

#define LT_MENU_NEW_MissionMenu0 "single player"
#define LT_MENU_NEW_MissionMenu1 "Start Game"
#define LT_MENU_NEW_MissionMenu2 "back"

#define LT_MENU_NEW_Start0 "single player"
#define LT_MENU_NEW_Start1 "single player"
#define LT_MENU_NEW_Start2 "death match"
#define LT_MENU_NEW_Start3 "Setup Biker"
#define LT_MENU_NEW_Start4 "Play demo"
#define LT_MENU_NEW_Start5 "load Game"
#define LT_MENU_NEW_Start6 "Options"
#define LT_MENU_NEW_Start7 "Exit"

#define LT_MENU_QuickTextSend0 "Message: "

#define LT_MENU_QuickTextSendWhisper0 "Whisper Message: "
									  
#define LT_MENU_EditMacro10 "Edit Message 1"
#define LT_MENU_EditMacro11 "Enter Message 1 "

#define LT_MENU_EditMacro20 "Edit Message 2"
#define LT_MENU_EditMacro21 "Enter Message 2 "

#define LT_MENU_EditMacro30 "Edit Message 3"
#define LT_MENU_EditMacro31 "Enter Message 3 "

#define LT_MENU_NEW_Team0 "select teams"
#define LT_MENU_NEW_Team1 "Red"
#define LT_MENU_NEW_Team2 "Green"
#define LT_MENU_NEW_Team3 "Blue"
#define LT_MENU_NEW_Team4 "Yellow"
#define LT_MENU_NEW_Team5 "Red"
#define LT_MENU_NEW_Team6 "Green"
#define LT_MENU_NEW_Team7 "Blue"
#define LT_MENU_NEW_Team8 "Yellow"
#define LT_MENU_NEW_Team9 "waiting for team selection"
#define LT_MENU_NEW_Team10 "msg:"

#define LT_MENU_NEW_WatchTeamSelect0 "select teams"
#define LT_MENU_NEW_WatchTeamSelect1 "Red"
#define LT_MENU_NEW_WatchTeamSelect2 "Green"
#define LT_MENU_NEW_WatchTeamSelect3 "Blue"
#define LT_MENU_NEW_WatchTeamSelect4 "Yellow"
#define LT_MENU_NEW_WatchTeamSelect5 "Red"
#define LT_MENU_NEW_WatchTeamSelect6 "Green"
#define LT_MENU_NEW_WatchTeamSelect7 "Blue"
#define LT_MENU_NEW_WatchTeamSelect8 "Yellow"
#define LT_MENU_NEW_WatchTeamSelect9 "waiting for team selection"
#define LT_MENU_NEW_WatchTeamSelect10 "msg:"

#define LT_MENU_NEW_ChooseTeamForExistingGame0 "select teams"
#define LT_MENU_NEW_ChooseTeamForExistingGame1 "Red"
#define LT_MENU_NEW_ChooseTeamForExistingGame2 "Green"
#define LT_MENU_NEW_ChooseTeamForExistingGame3 "Blue"
#define LT_MENU_NEW_ChooseTeamForExistingGame4 "Yellow"
#define LT_MENU_NEW_ChooseTeamForExistingGame5 "Red"
#define LT_MENU_NEW_ChooseTeamForExistingGame6 "Green"
#define LT_MENU_NEW_ChooseTeamForExistingGame7 "Blue"
#define LT_MENU_NEW_ChooseTeamForExistingGame8 "Yellow"
#define LT_MENU_NEW_ChooseTeamForExistingGame9 "msg:"

#define LT_MENU_LevelSelect0 "Level Selection"
#define LT_MENU_LevelSelect1 "Ability To Change "
#define LT_MENU_LevelSelect2 "Level..."

#define LT_MENU_SaveGame0 "Save Game"
#define LT_MENU_SaveGame1 "Choose From..."

#define LT_MENU_Keyboard0 "Configure controls"
#define LT_MENU_Keyboard1 "Rotate Left"
#define LT_MENU_Keyboard2 "Rotate Right"
#define LT_MENU_Keyboard3 "Rotate Up"
#define LT_MENU_Keyboard4 "Rotate Down"
#define LT_MENU_Keyboard5 "Slide Left"
#define LT_MENU_Keyboard6 "Slide Right"
#define LT_MENU_Keyboard7 "Slide Up"
#define LT_MENU_Keyboard8 "Slide Down"
#define LT_MENU_Keyboard9 "Roll Left"
#define LT_MENU_Keyboard10 "Roll Right"
#define LT_MENU_Keyboard11 "Slide Mode"
#define LT_MENU_Keyboard12 "Roll Mode"
#define LT_MENU_Keyboard13 "Forward"
#define LT_MENU_Keyboard14 "Reverse"
#define LT_MENU_Keyboard15 "Nitro"
#define LT_MENU_Keyboard16 "Speed Up"
#define LT_MENU_Keyboard17 "Slow Down"
#define LT_MENU_Keyboard18 "Fire Prim"
#define LT_MENU_Keyboard19 "Fire Sec"
#define LT_MENU_Keyboard20 "Drop Mine"
#define LT_MENU_Keyboard21 "Drop Prim"
#define LT_MENU_Keyboard22 "Drop Sec"
#define LT_MENU_Keyboard23 "Drop Shield"
#define LT_MENU_Keyboard24 "Drop Ammo"
#define LT_MENU_Keyboard25 "Pulsar"
#define LT_MENU_Keyboard26 "Trojax"
#define LT_MENU_Keyboard27 "Pyrolite"
#define LT_MENU_Keyboard28 "Transpulse"
#define LT_MENU_Keyboard29 "Suss Gun"
#define LT_MENU_Keyboard30 "Beam Laser"
#define LT_MENU_Keyboard31 "Next Prim"
#define LT_MENU_Keyboard32 "Prev Prim"
#define LT_MENU_Keyboard33 "Next Sec"
#define LT_MENU_Keyboard34 "Prev Sec"
#define LT_MENU_Keyboard35 "Send Msg"
#define LT_MENU_Keyboard36 "speech taunt"
#define LT_MENU_Keyboard37 "Mug Missile"
#define LT_MENU_Keyboard38 "Solaris"
#define LT_MENU_Keyboard39 "Scatter"
#define LT_MENU_Keyboard40 "Gravgon"
#define LT_MENU_Keyboard41 "MFRL"
#define LT_MENU_Keyboard42 "Titan Star"
#define LT_MENU_Keyboard43 "Purge Mine"
#define LT_MENU_Keyboard44 "Pine Mine"
#define LT_MENU_Keyboard45 "Quantum Mine"
#define LT_MENU_Keyboard46 "Thief Missile"
#define LT_MENU_Keyboard47 "Spider Mine"
#define LT_MENU_Keyboard48 "Show Messages"
#define LT_MENU_Keyboard49 "Show Statistics"
#define LT_MENU_Keyboard50 "Show Network Info"

#define LT_MENU_Controls0 "Bike Controls"
#define LT_MENU_Controls1 "Configure controls"
#define LT_MENU_Controls2 "Mouse             "
#define LT_MENU_Controls3 "Joystick          "
#define LT_MENU_Controls4 "Autoleveling      "
#define LT_MENU_Controls5 "Invert X          "
#define LT_MENU_Controls6 "Invert Y          "
#define LT_MENU_Controls7 "X Sensitivity     "
#define LT_MENU_Controls8 "Y Sensitivity     "

#define LT_MENU_Detail0 "Detail Levels"
#define LT_MENU_Detail1 "Bi Linear Filtering"
#define LT_MENU_Detail2 "Perspective Correct"
#define LT_MENU_Detail4 "Team Info          "
#define LT_MENU_Detail5 "Primary Lights     "
#define LT_MENU_Detail6 "Secondary Lights   "
#define LT_MENU_Detail7 "Pickup Lights      "
#define LT_MENU_Detail10 "Auto Detail        "
#define LT_MENU_Detail11 "Bike Detail        "
#define LT_MENU_Detail12 "Water Detail       "
#define LT_MENU_Detail13 "gamma              "
#define LT_MENU_Detail16 "Lightning Laser    "

#define LT_MENU_SelectBike0 "Select Bike"
#define LT_MENU_SelectBike1 "Choose From..."

#define LT_MENU_SelectBikeComputer0 "Select Bike Computer"
#define LT_MENU_SelectBikeComputer1 "Choose From..."

#define LT_MENU_NEW_ChangeBikeComputer0 "Select Bike Computer"
#define LT_MENU_NEW_ChangeBikeComputer1 "Choose bike computer..."
#define LT_MENU_NEW_ChangeBikeComputer2 "list..."
					 
#define LT_MENU_SelectScreenMode0 "Select Screen Mode"
#define LT_MENU_SelectScreenMode1 "Choose From..."

#define LT_MENU_SelectTextureFormat0 "Select Texture Format"
#define LT_MENU_SelectTextureFormat1 "Choose From..."

#define LT_MENU_Visuals0 "Visuals"
#define LT_MENU_Visuals1 "Select Screen Mode"
#define LT_MENU_Visuals2 "Select Texture Format"

#define LT_MENU_Options0 "Options"
#define LT_MENU_Options1 "Visuals"
#define LT_MENU_Options2 "Sound FX and Music"
#define LT_MENU_Options3 "Detail Levels"
#define LT_MENU_Options4 "Show Frame Rate "
#define LT_MENU_Options5 "Packets Per Second "
#define LT_MENU_Options7 "update (secs)"
#define LT_MENU_Options8 "Show Extra Info "
#define LT_MENU_Options9 "Show Weapon Kills"
#define LT_MENU_Options10 "Restore Defaults"
#define LT_MENU_Options11 "Show Statistics"
#define LT_MENU_Options13 "Show Players on HUD"

#define LT_MENU_SelfPlayOptions0 "Options"
#define LT_MENU_SelfPlayOptions1 "Select Screen Mode"
#define LT_MENU_SelfPlayOptions2 "Select Texture Format"
#define LT_MENU_SelfPlayOptions3 "Detail Levels"
#define LT_MENU_SelfPlayOptions4 "Show Player Names "
#define LT_MENU_SelfPlayOptions5 "Show Frame Rate "

#define LT_MENU_DemoPlaying0 "Demo Playing"
#define LT_MENU_DemoPlaying1 "Pause Demo "
#define LT_MENU_DemoPlaying2 "Playback Speed"
#define LT_MENU_DemoPlaying3 "Watch Player"
#define LT_MENU_DemoPlaying4 "Options"
#define LT_MENU_DemoPlaying5 "Quit to Main Menu"
#define LT_MENU_DemoPlaying6 "Grab 3dfx demo "
#define LT_MENU_DemoPlaying7 "Playback Speed"
#define LT_MENU_DemoPlaying8 "Watch Player"
#define LT_MENU_DemoPlaying9 "Options"
#define LT_MENU_DemoPlaying10 "Debugging"
#define LT_MENU_DemoPlaying11 "Quit to Title Screen"

#define LT_MENU_DemoPlayBack0 "Demo Playback"
#define LT_MENU_DemoPlayBack1 "Start"
#define LT_MENU_DemoPlayBack2 "Playback Speed"
#define LT_MENU_DemoPlayBack3 "Watch Player"
#define LT_MENU_DemoPlayBack4 "Choose From..."

#define LT_MENU_DemoCleaning0 "Clean A Demo"
#define LT_MENU_DemoCleaning1 "Start"
#define LT_MENU_DemoCleaning2 "Output Name  "
#define LT_MENU_DemoCleaning3 "Choose From..."

#define LT_MENU_SetUpBiker0 "Set Up Biker"
#define LT_MENU_SetUpBiker1 "Create New Biker  "
#define LT_MENU_SetUpBiker2 "Bike Controls"
#define LT_MENU_SetUpBiker3 "Select Bike"
#define LT_MENU_SetUpBiker4 "Select Bike Computer"
#define LT_MENU_SetUpBiker5 "Choose From..."

#define LT_MENU_Save0 "Save Menu"
#define LT_MENU_Save1 "Save Pickups"

#define LT_MENU_InGame0 "Forsaken"
#define LT_MENU_InGame1 "Set Up Biker  "
#define LT_MENU_InGame2 "Toggle Full Screen (Shift+F12)"
#define LT_MENU_InGame3 "Load Game"
#define LT_MENU_InGame4 "Save Game"
#define LT_MENU_InGame5 "Options"
#define LT_MENU_InGame6 "Level Select"
#define LT_MENU_InGame7 "End level and show stats"
#define LT_MENU_InGame8 "Quit to Main Menu"
#define LT_MENU_InGame11 "Debugging"
#define LT_MENU_InGame13 "Wireframe Mode"
#define LT_MENU_InGame14 "Save Menu"
#define LT_MENU_InGame15 "Debug Menu"
#define LT_MENU_InGame16 "IP "
#define LT_MENU_InGame17 "Packets Per Second "
#define LT_MENU_InGame18 "Set Up Biker  "
#define LT_MENU_InGame19 "Load Game"
#define LT_MENU_InGame20 "Save Game"
#define LT_MENU_InGame21 "options"
#define LT_MENU_InGame22 "Quit to Main Menu"
#define LT_MENU_InGame23 "Debugging"
#define LT_MENU_InGame24 "Watch Player"
#define LT_MENU_InGame25 "Quit to desktop"
#define LT_MENU_InGame26 "Host Options"
#define LT_MENU_InGame27 "Collision Perspective"
#define LT_MENU_InGame28 "normal kill messages "
#define LT_MENU_InGame29 "milestone kill messages "
#define LT_MENU_InGame30 "system messages "
#define LT_MENU_InGame31 "flag/bounty messages "
#define LT_MENU_InGame32 "player messages "
#define LT_MENU_InGame33 "pickup messages "
#define LT_MENU_InGame34 "taunt messages "
#define LT_MENU_InGame35 "your messages "
#define LT_MENU_InGame36 "short packets"

#define LT_MENU_Help0 "In-Game Help"
#define LT_MENU_Help1 "Toggle menu"
#define LT_MENU_Help2 "Toggle help screen" 
#define LT_MENU_Help3 "Increase window size" 
#define LT_MENU_Help4 "Decrease window size" 
#define LT_MENU_Help5 "Toggle panel text" 
#define LT_MENU_Help6 "Toggle remote camera" 
#define LT_MENU_Help7 "Toggle rear camera" 
#define LT_MENU_Help8 "Toggle missile camera" 
#define LT_MENU_Help9 "Toggle player names"
#define LT_MENU_Help10 "Return to game"

// note to translator: the ~ character in the next section represents a line break

#define LT_BorgBikerText "LOKASENNA IS AN AGENT OF PRO:BORG, A SECRET SOCIETY OBSESSED WITH THE EVOLUTION OF MANKIND THROUGH THE SYMBIOTIC INTEGRATION OF MIND AND MACHINE.~~THOSE THAT DO NOT AGREE WITH THE PRO:BORG DOCTRINE ARE REMOVED WITH CLINICAL EFFICIENCY."
#define LT_BeardBikerText "BEARD'S A HEAD-BANGIN' HARD MOTHER. HE RIDES THE SPACELANES ON A BROUGH SUPERIOR 119, ACCOMPANIED BY HIS long DEAD PARTNER 'MAD-DOG MCCOY'. TOGETHER THEY'RE ALWAYS ON THE LOOKOUT FOR SERIOUS METAL MAYHEM!~~LET'S ROCK!!!"
#define LT_LAJayBikerText "L.A. JAY HAS long BEEN SURFING THE SOLAR WAVES; A MAN WHOSE OVER-THE-TOP ATTITUDE IS MATCHED ONLY BY THE BRIGHTNESS OF HIS SHIRT.~~L.A. IS NOT SO CONCERNED ABOUT WHAT HE'S DOING, SO long AS HE LOOKS COOL WHILE DOING IT."
#define LT_ExCopBikerText "THE MEANEST BEAT COP EVER, EX-COP WAS THROWN OUT OF THE FORCE AFTER A FRENZIED DRUGS BUST SAW HIM TAKE DOWN NINE STREET PUNKS AND THREE FELLOW OFFICERS. EX-COP SAID IT WAS HIS LATENT TRIGGER HAPPY MENTALITY. BESIDES, 'WHY LOCK PEOPLE UP WHEN YOU CAN BLOW 'EM AWAY?'"
#define LT_TruckerBikerText "ANYONE WHO HAS PASSED THROUGH SOME OF THE SEEDIER INTERSTELLAR TRUCKSTOPS WOULD MOST DEFINITELY HAVE HEARD ABOUT THE BADDEST TRUCKER OF THEM ALL... REX HARDY.THE TALES OF HARDY'S WILD AND VIOLENT LIFE-STYLE HAVE ELEVATED HIM TO THE STATUS OF FEARED, AND RESPECTED, TRUCKER GOD."
#define LT_FoetoedBikerText "A HIDEOUS GENETIC MUTATION CONTAINED WITHIN A LIFE SUSTAINING STEEL WOMB, THE THING KNOWN ONLY AS FOETOID BRINGS DEATH AND DESTRUCTION TO ALL WHO WOULD STAND IN ITS WAY.~~NO HUMAN CONSCIENCE CLOUDS ITS THOUGHTS, AND NO SHRED OF MORALITY HINDERS ITS ACTIONS."
#define LT_JapBirdBikerText "BEING A WILD AND VIOLENT PSYCHOTIC ITS NO SURPRISE THAT NIM SOO SUN HAS EARNT HERSELF THE NICKNAME 'THE BABE WITH THE BLADES'. AN EX-MEMBER OF THE GRUESOME XENO-CIRCUS, SHE NOW WORKS FREELANCE SELLING ANCIENT RELICS PLUNDERED FROM CONDEMNED WORLDS. EARTH IS HER NEXT DESTINATION..."
#define LT_NuttaBikerText "NUTTA WAS ONCE AN EMINENT PHYSICIAN AND A MODEL CITIZEN. HOWEVER, BENEATH THIS FACADE LAY A TORTURED AND DERANGED MIND. THE DOCTOR WAS FINALLY COMMITED AFTER TRYING TO ANAESTHETIZE A PATIENT WITH A SLEDGEHAMMER! THE DOCTOR HAS NOW BEEN RELEASED, APPARENTLY CURED, UPON AN UNSUSPECTING WORLD."
#define LT_SceptreBikerText "DESPITE BEING DEFORMED BY A GRUESOME GENETIC DISEASE, SCEPTRE HAS STILL ELEVATED HIS STATUS TO THAT OF THE TRULY FEARED AND DESPISED.~~IN THE LAST FEW YEARS HE HAS STAMPED HIS IRON WILL ON SEVERAL WORLDS AND BROUGHT THEIR TERRIFIED POPULATIONS TO HEEL." 
#define LT_JoBikerText "HE IS THE ULTIMATE COMPUTER JUNKIE; A LAID BACK SLACKER ATTITUDE, MARRIED TO A HARDCORE TECHNO OBSESSION.~~JO IS IN THIS LINE OF WORK FOR JUST ONE REASON, HIS LOVE OF CYBER-JUNK, SMART WEAPONS AND GADGETRY."
#define LT_SharkBikerText "CUVEL IS YOUR AVERAGE, CUNNING, DOUBLE-CROSSING, GAMBLING, SWINDLER... AND THEN SOME. HE KNOWS WHERE THE MONEY'S TO BE MADE AND HOW TO GET IT.~~WHY WORK FOR SOMETHING WHEN YOU CAN STEAL IT?" 
#define LT_HK5BikerText "HK-5 REPRESENTS THE PINNACLE OF COMPUTER CONTROLLED ATTACK CRAFT TECHNOLOGY GONE WRONG. ITS SILICON BRAIN IS INFECTED WITH MEGALOMANIA, GREED AND LOATHING FOR ALL HUMANOID LIFEFORMS.~~GENOCIDE IS ITS ONLY DESIRE."
#define LT_NubiaBikerText "NUBIA SPECIALIZES IN ARMED ROBBERY AND CONTRACT KILLINGS.~~MORE RECENTLY, SHE HAS ALSO DABBLED WITH COMPUTER CRIME AND FRAUD. NO ONE HAS CROSSED HER AND LIVED TO TELL THE TALE.~~A MEANER BITCH YOU'D BE HARD PRESSED TO FIND."
#define LT_MophistoBikerText "TTEC IV'S. THE LATEST MULTI-PURPOSE COMBAT DROIDS. IN 2112, ALL WERE ORDERED DESTROYED DUE TO DEFECTIVE CONTROL CIRCUITRY. MOFISTO WAS A TTEC IV. THE NEWS OF HIS IMMINENT SHUTDOWN DIDN'T SIT WELL WITH HIS SURVIVAL CODE. PURE PUMPING METAL DEVASTATION JUST HIT THE STREETS!"
#define LT_CerberoBikerText "CERBERO: THE MAN-MACHINE BOUNTY HUNTER WHO PREYS ON THE SCUM OF THE UNIVERSE. A TITANIUM HEART, TOXIN RESISTANT LUNGS AND I.R. SENSITIVE EYES ARE JUST A FEW OF THE BODILY ALTERATIONS WHICH HAVE TURNED HIM INTO A COLD AND CLINICAL KILLER."
#define LT_SleekBikerText "EARL IS THE FLYEST FUNKMEISTER THIS SIDE OF THE GALAXY. EARL HAS DEALT HIMSELF INTO THIS LINE OF WORK SENSING AN EASY PROFIT. NO ONES GOT THE BALLS TO TAKE OUT DA EARL, AND HE KNOWS IT. 'HEY BABY, THE MAN'S IN TOWN'."
#define LT_FlygirlBikerText "Little is known about this strange and enigmatic being. Dubbed 'flygirl' by those mercenaries that have escaped her clutches, some say she is Earth's last survivor; an adult with the mind of a child, and an evil mind at that. She is seldom seen, but never forgotten."

#define LT_ToggleStatusOn "on"
#define LT_ToggleStatusOff "off"
#define LT_ToggleStatusShooter "shooter"
#define LT_ToggleStatusTarget "target"

// Custom message colours
#define LT_WHITE "white"
#define LT_RED "red"
#define LT_LIGHTGREEN "light green"
#define LT_BLUE "blue"
#define LT_YELLOW "yellow"
#define LT_LIGHTBLUE "light blue"
#define LT_PINK "pink"
#define LT_TURQUOISE "turquoise"
#define LT_GREY "grey"
#define LT_DISABLED "disabled"

#define LT_Undef "undef"	// ( short for undefined )
#define LT_SelectWhenReady "Select when ready"
#define LT_WaitingForReset "Waiting..."

#define LT_PageNo "Page %d of %d"	// %d = number
#define LT_PageDown	"  [Page Down]=more"
#define LT_PageUpDown "  [Page Up/Down]=more"
#define LT_PageUp "  [Page Up]=more"
#define LT_PressKey "press key or button for %s"	// %s will be name of action
#define LT_ViewAlternateKeys "[right]=view alternate keys for %s"	// %s = action
#define LT_ViewAlternateKeys2 "[left]=view alternate keys for %s"	// %s = action
#define LT_SelectControl "[up/down]=select control" 
#define LT_Cancel "[esc]=cancel" 
#define LT_Edit "[enter]=edit, [del]=remove key for %s"	// %s = action
#define LT_Add "[enter]=add, [del]=remove key for %s"	// %s = action

#define LT_Unconnected1 " is not connected"
#define LT_Unconnected2 " unconnected"
#define LT_AlsoControls "[%s] also controls "

#define LT_ToggleOn " ON"  
#define LT_ToggleOff " OFF"
#define LT_ToggleShooter " SHOOTER"  
#define LT_ToggleTarget " TARGET"
#define LT_Undef "undef"	// short for undefined 

#define LT_QuitToMainMenu "Quit to Main Menu"

#define LT_SavedGameName "saved %d-%d-%d at %2d:%02d"	// %d-%d-%d is day-month-year %2d:%02d is time
#define LT_LevelName "level name: %s"	// %s is name of level
#define LT_LevelPlayedFor1 "%s played for %hd mins %hd secs"	// %s = player name, %hd = num mins, %hd = num secs  
#define LT_LevelPlayedFor2 "played for %hd mins %hd secs"		// %s = player name, %hd = num mins, %hd = num secs  
#define LT_EnemiesKilled "enemies killed: %hd of %hd"	// %hd = number 

#define LT_NoSavedGamesFound "no saved games found"

#define LT_NoLimit "no limit"
#define LT_OneMinute "1 min"
#define LT_ManyMinutes "%d mins"	// %d = num minutes 
#define LT_NoValue "no value" 

#define LT_SpaceOrb "You must use spaceware to set up the spaceball axis"

#define LT_NoJoysticks "No Joysticks Connected~~(you cannot connect a joystick while the game is running)"	// ~~ = newline  

#define LT_OneCrystalFound "%d crystal found so far"	// %d is number of crystals
#define LT_CrystalsFound "%d crystals found so far"	// %d is number of crystals

#define	LT_OneSecretFoundOutOf "%d secret found out of %d"
#define	LT_SecretsFoundOutOf "%d secrets found out of %d"

#define LT_OneGoldBarFound "%d gold bar found so far"	// %d is number of gold bars 
#define LT_GoldBarsFound "%d gold bars found so far"	// %d is number of gold bars 

#define LT_OneEnemyKilled "%d enemy killed out of %d" 
#define LT_EnemysKilled "%d enemies killed out of %d" 

#define LT_TimeTaken1 "time taken %d min %d sec" 
#define LT_TimeTaken2 "time taken %d mins %d sec" 
#define LT_TimeTaken3 "time taken %d min %d secs" 
#define LT_TimeTaken4 "time taken %d mins %d secs"

#define LT_CTF_Normal "normal"
#define LT_CTF_MustCarry "carry it back"
#define LT_CTF_CanCarry "can pick up"
#define LT_CTF_OneTouch "1 touch return"
#define LT_CTF_NoReturn "can't pick up"
#define LT_CTF_Standard "standard"

/*********************************************************************

  ADDED SINCE FULL RELEASE

*********************************************************************/
#define LT_MENU_Keyboard1a "headlights"
#define LT_MENU_Keyboard1b "full rear view"

#define LT_MENU_RemovePlayer "remove player"

#define LT_MENU_NEW_ChooseConnectionToStart1 "press 'esc' to quit"

#define LT_Extra3 "session created %d-%d-%d at %02d:%02d"
#define LT_Extra4 "level: %s"
#define LT_Extra5 "players: %d / %d"
#define LT_Extra6 "game: %s%s"
#define LT_Extra7 "packets: short %s"
#define LT_Extra8 "collision perspective: %s"
#define LT_Extra11 "kills limit %d ( current top %d )"
#define LT_Extra12 "time limit %d mins ( %d left )"

#define LT_NoLevelsInstalled "no levels installed!"
#define LT_NoSinglePlayerLevelsInstalled "no single player levels installed!"

#define LT_Extra1b "%d packets per second"
#define LT_MENU_Detail1a "Tri Linear Filtering"
#define LT_MENU_NEW_MoreMultiplayerOptions1a "target collision perspective"
#define LT_MENU_NEW_MoreMultiplayerOptions2a "shooter collision perspective"
#define KICKED_HOST "you have been kicked out by the host"
#define DID_NOT_HAVE_LEVEL "you did not have the level chosen by the host ( %s )"
#define PLEASE_WAIT "please wait..."

#endif // LOCALTITLE_INCLUDED

