
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Kscale.RC
//

#define IDS_FILTERSTRING                1
#define IDS_FILTERSTRING_AVI            1
#define IDS_FILTERSTRING_BMP            2
#define IDDEFAULT                       3
#define IDD_COLORCONTROL                104
#define IDD_INDEOVIDEOR4                105
#define IDD_SCALABILITYCONTROL0         106
#define IDD_ACCESSKEYCONTROL            107
#define IDD_SCALABILITY                 110
#define IDD_SCALABILITYCONTROL          110
#define IDR_MENUCLOSED                  112
#define IDR_MENUOPENED                  113
#define IDD_INFO                        114
#define IDD_INFOR4                      115
#define IDD_INFOSHORTCUTS               116
#define IDD_TRACKSEEK                   117
#define IDB_PLAY                        118
#define IDR_MENUSTUFF                   122
#define IDD_IVI_DLG                     124
#define IDC_TRACKBUTTON                 1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_TB_COLORCONTROL_BRIGHTNESS  1002
#define IDC_BUTTON4                     1003
#define IDC_BUTTON5                     1004
#define IDC_BUTTON6                     1005
#define ID_MOVIE_FORWARD                1005
#define IDC_TB_COLORCONTROL_SATURATION  1008
#define IDC_TB_COLORCONTROL_CONTRAST    1009
#define IDC_TB_COLORCONTROL_TIMESLICE   1012
#define IDC_CHECK1                      1014
#define IDC_INFO_SCALABILITY            1014
#define IDC_EDIT1                       1015
#define IDC_EDIT_KEY                    1015
#define IDC_INFO_BIDIR                  1015
#define IDC_COMBO1                      1016
#define IDC_INFO_TRANSPARENCY           1016
#define IDC_INFO_ACCESSKEY              1017
#define IDC_EDIT3                       1017
#define IDC_EB_SATURATION               1017
#define IDC_TB_SCALABILITYCONTROL_CPUPERCENTAGE 1018
#define IDC_EDIT4                       1018
#define IDC_EB_CONTRAST                 1018
#define IDC_EDIT5                       1019
#define IDC_EB_BRIGHTNESS               1019
#define IDC_TEXT_COLORCONTROL_BRIGHTNESS 1020
#define IDC_EDIT6                       1020
#define IDC_EB_LD_X                     1020
#define IDC_TEXT_COLORCONTROL_SATURATION 1021
#define IDC_EDIT7                       1021
#define IDC_EB_LD_Y                     1021
#define IDC_TEXT_COLORCONTROL_CONTRAST  1022
#define IDC_EDIT8                       1022
#define ICD_EB_LD_DX                    1022
#define IDC_EB_LD_DX                    1022
#define IDC_EDIT9                       1023
#define IDC_EB_LD_DY                    1023
#define IDC_TEXT_SCALABILITYCONTROL_CPUPERCENTAGE 1024
#define IDC_EB_LD_X2                    1024
#define IDC_CB_SCALABILITYCONTROL_EQUIVALENTPROCESSOR 1025
#define IDC_EB_LD_Y2                    1025
#define IDC_TB_SCALABILITYCONTROL_MSPERFRAME 1026
#define IDC_TB_MSPERFRAME               1026
#define IDC_EB_LD_DX2                   1026
#define IDC_CB_SCALABILITYCONTROL_PROCESSOR 1027
#define IDC_CB_PROCESSOR                1027
#define IDC_EB_LD_DY2                   1027
#define IDC_TEXT_SCALABILITYCONTROL_MSPERFRAME 1028
#define IDC_TEXT_MSPERFRAME             1028
#define IDC_RADIO1                      1029
#define IDC_RADIO_PROCESSOR             1029
#define IDC_INFO_LOW                    1029
#define IDC_RADIO_MSPERFRAME            1030
#define IDC_INFO_MEDIUM                 1030
#define IDC_TEXT_TITLE_PROCESSOR        1031
#define IDC_INFO_HIGH                   1031
#define IDC_TEXT_TITLE_MSPERFRAME       1032
#define IDC_TEXT_MS00                   1034
#define IDC_TEXT_MS10                   1035
#define IDC_TEXT_MS01                   1036
#define IDC_TEXT_MS02                   1037
#define IDC_TEXT_MS03                   1038
#define IDC_TEXT_MS04                   1039
#define IDC_TEXT_MS05                   1040
#define IDC_TEXT_MS11                   1041
#define IDC_TEXT_MS12                   1042
#define IDC_TEXT_MS13                   1043
#define IDC_EDIT_PROCESSOR              1044
#define IDC_INFO_WIDTH                  1047
#define IDC_INFO_HEIGHT                 1048
#define IDC_INFO_FILENAME               1048
#define IDC_INFO_MEDIALENGTH            1049
#define IDC_INFO_AUDIOFMT               1050
#define IDC_INFO_VIDEORES               1051
#define IDC_INFO_VIDEOFRAMES            1052
#define IDC_INFO_VIDEOFPS               1053
#define IDC_INFO_VIDEOFOURCC            1054
#define IDC_INFO_DATARATE               1055
#define IDC_INFO_VERSIONSTR             1056
#define IDC_TRACKMOVE                   1058
#define IDC_GENERIC5                    1063
#define IDC_TB_SATURATION               1063
#define IDC_GENERIC6                    1064
#define IDC_GENERIC7                    1065
#define IDC_TB_CONTRAST                 1065
#define IDC_GENERIC8                    1066
#define IDC_GENERIC9                    1067
#define IDC_TB_BRIGHTNESS               1067
#define IDC_GENERIC10                   1068
#define IDC_EDIT10                      1069
#define IDC_CHECK2                      1070
#define IDC_RADIO2                      1071
#define IDC_RADIO3                      1072
#define IDC_EDIT11                      1073
#define IDC_RADIO5                      1078
#define IDC_RADIO6                      1079
#define IDC_RADIO7                      1080
#define IDC_EDIT13                      1082
#define IDC_EDIT14                      1083
#define IDC_EDIT17                      1086
#define IDC_EDIT15                      1087
#define IDC_EDIT16                      1088
#define IDC_EDIT18                      1089
#define IDC_EDIT19                      1090
#define IDC_UD_BRIGHTNESS               1095
#define IDC_UD_CONTRAST                 1096
#define IDC_UD_SATURATION               1097
#define IDC_LD_PREVIEW                  1101
#define IDC_LD_PREVIEW1                 1102
#define IDC_DISABLE_LD                  1103
#define IDC_APPLY_LD                    1104
#define IDC_ENABLE_LD                   1105
#define IDC_OK                          1106
#define IDC_USER2                       1109
#define ID_FILE_OPEN                    50001
#define ID_FILE_CLOSE                   50002
#define ID_MOVIE_PLAY                   50003
#define ID_MOVIE_STOP                   50004
#define ID_MOVIE_REWIND                 50006
#define ID_MOVIE_PLAYBAR                50007
#define ID_OPTIONS_BITDEPTH_CLUT8       50008
#define ID_OPTIONS_BITDEPTH_RGB16       50009
#define ID_OPTIONS_BITDEPTH_RGB16_555   50010
#define ID_OPTIONS_BITDEPTH_RGB16_565   50011
#define ID_OPTIONS_BITDEPTH_RGB24       50012
#define ID_OPTIONS_BITDEPTH_RGB32       50013
#define ID_OPTIONS_RESOLUTION_NATIVE    50014
#define ID_OPTIONS_RESOLUTION_ZOOMBY2   50015
#define ID_OPTIONS_RESOLUTION_OTHER     50017
#define ID_OPTIONS_RESOLUTION_ZOOMBY2ALT 50017
#define ID_OPTIONS_INDEOVIDEOR4_COLORCONTROLS 50018
#define ID_OPTIONS_INDEOVIDEOR4_ACCESSKEY 50019
#define ID_OPTIONS_INDEOVIDEOR4_SCALABILITY 50020
#define ID_MOVIE_LOOP                   50021
#define ID_MOVIE_STATISTICS             50023
#define ID_MOVIE_PAUSE                  50024
#define ID_MOVIE_REDRAW                 50025
#define ID_MOVIE_STEPBACK               50026
#define ID_MOVIE_STEPFORWARD            50027
#define ID_MOVIE_PLAYPAUSE              50029
#define ID_MOVIE_INFO                   50031
#define ID_MOVIE_PAGEBACK               50032
#define ID_MOVIE_PAGEFORWARD            50033
#define ID_MOVIE_SECBACK                50034
#define ID_MOVIE_SECFORWARD             50035
#define ID_MOVIE_SEEKBAR                50037
#define ID_OPTIONS_PALETTE_NATIVE       50043
#define ID_OPTIONS_PALETTE_CLIPBOARD    50044
#define ID_OPTIONS_PALETTE_GRAY         50045
#define ID_OPTIONS_INDEOVIDEOR4_TRANSPARENCY_SETBACKGROUND 50046
#define ID_OPTIONS_PALETTE_LOAD         50047
#define ID_OPTIONS_PALETTE_FILE         50047
#define ID_OPTIONS_INDEOVIDEOR4_CONTROLS 50048
#define ID_OPTIONS_INDEOVIDEOR4_SETBACKGROUND 50049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
