
#ifndef LOCALTITLE_INCLUDED
#define LOCALTITLE_INCLUDED

#define LT_MacroText1 "tú, sucio hijo de perra..." 
#define LT_MacroText2 "Es hora de morir..." 
#define LT_MacroText3 "Te arrancaré el alma..."

#define LT_GameCompleteWithoutCrystals "bien hecho. Has completado todos los niveles mas no conseguiste todos los cristales. Tienes que volver a  hacerlo todo si quieres una recompensa adecuada."
#define LT_GameCompleteGotAllCrystalsSoFar "bien hecho, tienes todos los cristales. Toma una vida extra para el nivel secreto. Halla aquí el cristal para un premio especial."
#define LT_GameCompleteWithAllCrystals "bien hecho, tienes todos los cristales. Se te declara merenario secreto."
#define LT_GameCompleteWithAllCrystalsExceptLast "pasaste por el nivel secreto, mas no obtuviste el cristal final. Mejor suerte la próxima."
#define LT_GameCompleteWithCheating "bien, completaste el juego pero hiciste trampa, ¿no? Si quieres ver el nivel secreto y tener la oportunidad de ganar una recompensa especial, tienes que hacerlo correctamente."
#define LT_GameCompleteAdditionalLevels "enhorabuena. Has completado todos los niveles adicionales actualmente instalados. ¡¡Busca packs de misión adicionales!!"

#define LT_MENU_NEW_SpecialMessage0 "ok"

#define LT_MENU_NEW_NumberOfSecretsEnemys0 "ok"

#define LT_MENU_NEW_NumberOfGoldBars0 "ok"

#define LT_MENU_NEW_NumberOfCrystals0 "ok"

#define LT_MENU_NEW_StartSinglePlayer0 "Juego de Un Jugador" 
#define LT_MENU_NEW_StartSinglePlayer1 "comenzar" 
#define LT_MENU_NEW_StartSinglePlayer2 "nivel" 

#define LT_MENU_NEW_Error0 "ok"

#define LT_MENU_NEW_GeneralLoading0 "cargando..."

#define LT_MENU_NEW_StartAttractMode0 "cargando..."

#define LT_MENU_NEW_HostWaitingToStart0 "esperando para comenzar..." 
#define LT_MENU_NEW_HostWaitingToStart1 "comenzar" 
#define LT_MENU_NEW_HostWaitingToStart2 "IP:" 
#define LT_MENU_NEW_HostWaitingToStart3 "Num de Jugadores" 
#define LT_MENU_NEW_HostWaitingToStart4 "msg:" 

#define LT_MENU_NEW_ValidPickups0 "recogidas permitidas"
#define LT_MENU_NEW_ValidPickups1 "trojax"
#define LT_MENU_NEW_ValidPickups2 "pirolita"
#define LT_MENU_NEW_ValidPickups3 "transpulso"
#define LT_MENU_NEW_ValidPickups4 "cañón perforador"
#define LT_MENU_NEW_ValidPickups5 "láser"
#define LT_MENU_NEW_ValidPickups6 "mug"
#define LT_MENU_NEW_ValidPickups7 "solaris"
#define LT_MENU_NEW_ValidPickups8 "desarmador"
#define LT_MENU_NEW_ValidPickups9 "gravgon"
#define LT_MENU_NEW_ValidPickups10 "lmcf"
#define LT_MENU_NEW_ValidPickups11 "titan"
#define LT_MENU_NEW_ValidPickups12 "mina purgante"
#define LT_MENU_NEW_ValidPickups13 "mina revitalizadora"
#define LT_MENU_NEW_ValidPickups14 "mina cuántica"
#define LT_MENU_NEW_ValidPickups15 "invulnerabilidad"
#define LT_MENU_NEW_ValidPickups16 "nitro"
#define LT_MENU_NEW_ValidPickups17 "invisibilidad"
#define LT_MENU_NEW_ValidPickups18 "pulsar orbital"
#define LT_MENU_NEW_ValidPickups19 "tanque energético dorado"

#define LT_MENU_NEW_MoreMultiplayerOptions0 "Opciones Varios Jugadores"
#define LT_MENU_NEW_MoreMultiplayerOptions1 "tolerancia retraso"
#define LT_MENU_NEW_MoreMultiplayerOptions2 "paquetes cortos"
#define LT_MENU_NEW_MoreMultiplayerOptions3 "grupos paquetes" 
#define LT_MENU_NEW_MoreMultiplayerOptions4 "velocidad paquetes" 
#define LT_MENU_NEW_MoreMultiplayerOptions5 "mostrar impacto" 
#define LT_MENU_NEW_MoreMultiplayerOptions6 "intervalo impacto" 
#define LT_MENU_NEW_MoreMultiplayerOptions7 "escape vehiculo" 
#define LT_MENU_NEW_MoreMultiplayerOptions8 "vehic. brillantes" 
#define LT_MENU_NEW_MoreMultiplayerOptions9 "dañar comp equipo" 
#define LT_MENU_NEW_MoreMultiplayerOptions10 "Botín adicional" 
#define LT_MENU_NEW_MoreMultiplayerOptions11 "marcador captura banderas" 
#define LT_MENU_NEW_MoreMultiplayerOptions12 "intervalo botín adicional" 
#define LT_MENU_NEW_MoreMultiplayerOptions13 "norma bandera propia" 
#define LT_MENU_NEW_MoreMultiplayerOptions14 "grabar demo"
#define LT_MENU_NEW_MoreMultiplayerOptions15 "nombre demo "
#define LT_MENU_NEW_MoreMultiplayerOptions16 "daño causado cuando..."
#define LT_MENU_NEW_MoreMultiplayerOptions17 "creo mis disparos te tocaron"
#define LT_MENU_NEW_MoreMultiplayerOptions18 "creo tus disparos me tocaron"
#define LT_MENU_NEW_MoreMultiplayerOptions19 "cambiar recogidas permitidas"
#define LT_MENU_NEW_MoreMultiplayerOptions20 "recogidas al azar"

#define LT_MENU_NEW_CreateGame0 "Crear Juego Varios Jugadores"
#define LT_MENU_NEW_CreateGame1 "Comenzar juego"
#define LT_MENU_NEW_CreateGame2 "IP:"
#define LT_MENU_NEW_CreateGame3 "nombre sesión"
#define LT_MENU_NEW_CreateGame4 "nivel"
#define LT_MENU_NEW_CreateGame5 "límite jugador"
#define LT_MENU_NEW_CreateGame6 "límite tantos"
#define LT_MENU_NEW_CreateGame7 "límite tiempo"
#define LT_MENU_NEW_CreateGame8 "tipo juego"
#define LT_MENU_NEW_CreateGame9 "libre para todo"
#define LT_MENU_NEW_CreateGame10 "juego equipo"
#define LT_MENU_NEW_CreateGame11 "capturar bandera"
#define LT_MENU_NEW_CreateGame12 "perseguir bandera"
#define LT_MENU_NEW_CreateGame13 "perseguir botín"
#define LT_MENU_NEW_CreateGame14 "Perseguir botín equipo"
#define LT_MENU_NEW_CreateGame15 "etiqueta"
#define LT_MENU_NEW_CreateGame16 "más opciones"
#define LT_MENU_NEW_CreateGame17 "salir"

#define LT_MENU_NEW_CreateLobbyGame0 "Crear Juego Varios Jugadores"
#define LT_MENU_NEW_CreateLobbyGame1 "Comenzar juego"
#define LT_MENU_NEW_CreateLobbyGame2 "IP:"
#define LT_MENU_NEW_CreateLobbyGame3 "nombre sesión"
#define LT_MENU_NEW_CreateLobbyGame4 "nivel"
#define LT_MENU_NEW_CreateLobbyGame5 "límite jugador"
#define LT_MENU_NEW_CreateLobbyGame6 "límite puntos"
#define LT_MENU_NEW_CreateLobbyGame7 "límite tiempo"
#define LT_MENU_NEW_CreateLobbyGame8 "tipo juego"
#define LT_MENU_NEW_CreateLobbyGame9 "libre para todo"
#define LT_MENU_NEW_CreateLobbyGame10 "juego equipo"
#define LT_MENU_NEW_CreateLobbyGame11 "capturar bandera"
#define LT_MENU_NEW_CreateLobbyGame12 "perseguir botín"
#define LT_MENU_NEW_CreateLobbyGame13 "Perseguir botín equipo"
#define LT_MENU_NEW_CreateLobbyGame14 "etiqueta"
#define LT_MENU_NEW_CreateLobbyGame15 "más opciones"
#define LT_MENU_NEW_CreateLobbyGame16 "salir"

#define LT_MENU_NEW_ChooseConnectionToStart0 "Selecciona tipo conexión"

#define LT_MENU_NEW_PrimaryOrder0 "preferencias selección arma primaria"
#define LT_MENU_NEW_PrimaryOrder1 "auto"
#define LT_MENU_NEW_PrimaryOrder2 "manual"

#define LT_MENU_NEW_SecondaryOrder0 "preferencia selección arma secundaria"
#define LT_MENU_NEW_SecondaryOrder1 "auto"
#define LT_MENU_NEW_SecondaryOrder2 "manual"

#define LT_MENU_NEW_SecondaryWeaponKeys0 "arma secundaria"
#define LT_MENU_NEW_SecondaryWeaponKeys1 "disparar secundaria"
#define LT_MENU_NEW_SecondaryWeaponKeys2 "soltar mina"
#define LT_MENU_NEW_SecondaryWeaponKeys3 "misil mug"
#define LT_MENU_NEW_SecondaryWeaponKeys4 "misil solaris"
#define LT_MENU_NEW_SecondaryWeaponKeys5 "misil desarmar"
#define LT_MENU_NEW_SecondaryWeaponKeys6 "misil gravgon "
#define LT_MENU_NEW_SecondaryWeaponKeys7 "lmcf"
#define LT_MENU_NEW_SecondaryWeaponKeys8 "Misil Titán "
#define LT_MENU_NEW_SecondaryWeaponKeys9 "mina purgante"
#define LT_MENU_NEW_SecondaryWeaponKeys10 "mina revital."
#define LT_MENU_NEW_SecondaryWeaponKeys11 "mina cuántica"
#define LT_MENU_NEW_SecondaryWeaponKeys12 "prox. arma"
#define LT_MENU_NEW_SecondaryWeaponKeys13 "arma amteraor"
#define LT_MENU_NEW_SecondaryWeaponKeys14 "soltar arma"
#define LT_MENU_NEW_SecondaryWeaponKeys15 "disparar secundaria"
#define LT_MENU_NEW_SecondaryWeaponKeys16 "soltar mina"
#define LT_MENU_NEW_SecondaryWeaponKeys17 "misil mug"
#define LT_MENU_NEW_SecondaryWeaponKeys18 "misil solaris"
#define LT_MENU_NEW_SecondaryWeaponKeys19 "misil desarmar"
#define LT_MENU_NEW_SecondaryWeaponKeys20 "misil gravgon"
#define LT_MENU_NEW_SecondaryWeaponKeys21 "lmcf"
#define LT_MENU_NEW_SecondaryWeaponKeys22 "Misil Titán"
#define LT_MENU_NEW_SecondaryWeaponKeys23 "mina purgante"
#define LT_MENU_NEW_SecondaryWeaponKeys24 "mina revital."
#define LT_MENU_NEW_SecondaryWeaponKeys25 "mina cuántica"
#define LT_MENU_NEW_SecondaryWeaponKeys26 "Arma siguiente"
#define LT_MENU_NEW_SecondaryWeaponKeys27 "Arma presa"
#define LT_MENU_NEW_SecondaryWeaponKeys28 "soltar arma"

#define LT_MENU_NEW_PrimaryWeaponKeys0 "arma primaria"
#define LT_MENU_NEW_PrimaryWeaponKeys1 "disparar primaria"
#define LT_MENU_NEW_PrimaryWeaponKeys2 "pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys3 "trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys4 "pirolita"
#define LT_MENU_NEW_PrimaryWeaponKeys5 "transpulso"
#define LT_MENU_NEW_PrimaryWeaponKeys6 "cañón perforador"
#define LT_MENU_NEW_PrimaryWeaponKeys7 "láser"
#define LT_MENU_NEW_PrimaryWeaponKeys8 "Próxima arma"
#define LT_MENU_NEW_PrimaryWeaponKeys9 "Arma presa"
#define LT_MENU_NEW_PrimaryWeaponKeys10 "soltar arma"
#define LT_MENU_NEW_PrimaryWeaponKeys11 "enviar msg"
#define LT_MENU_NEW_PrimaryWeaponKeys12 "disparar primaria"
#define LT_MENU_NEW_PrimaryWeaponKeys13 "pulsar"
#define LT_MENU_NEW_PrimaryWeaponKeys14 "trojax"
#define LT_MENU_NEW_PrimaryWeaponKeys15 "cañor perfo."
#define LT_MENU_NEW_PrimaryWeaponKeys16 "pirolita"
#define LT_MENU_NEW_PrimaryWeaponKeys17 "transpulso"
#define LT_MENU_NEW_PrimaryWeaponKeys18 "láser"
#define LT_MENU_NEW_PrimaryWeaponKeys19 "Próxima arma"
#define LT_MENU_NEW_PrimaryWeaponKeys20 "Arma presa"
#define LT_MENU_NEW_PrimaryWeaponKeys21 "soltar arma"

#define LT_MENU_NEW_Weapons0 "armas"
#define LT_MENU_NEW_Weapons1 "teclas armas primarias"
#define LT_MENU_NEW_Weapons2 "teclas armas secundarias"
#define LT_MENU_NEW_Weapons3 "preferencias armas primarias"
#define LT_MENU_NEW_Weapons4 "preferencia armas secundarias"

#define LT_MENU_NEW_ConfigureKeyboard0 "controles movimiento"
#define LT_MENU_NEW_ConfigureKeyboard1 "rotar izqierda"
#define LT_MENU_NEW_ConfigureKeyboard2 "rotar derecha"
#define LT_MENU_NEW_ConfigureKeyboard3  "rotar arriba"
#define LT_MENU_NEW_ConfigureKeyboard4 "rotar abajo"
#define LT_MENU_NEW_ConfigureKeyboard5 "deslizar izquierda"
#define LT_MENU_NEW_ConfigureKeyboard6 "deslizar derecha"
#define LT_MENU_NEW_ConfigureKeyboard7 "deslizar arriba"
#define LT_MENU_NEW_ConfigureKeyboard8 "deslizar abajo"
#define LT_MENU_NEW_ConfigureKeyboard9 "rodar izquierda"
#define LT_MENU_NEW_ConfigureKeyboard10 "rodar derecha"
#define LT_MENU_NEW_ConfigureKeyboard11 "modo deslizar"
#define LT_MENU_NEW_ConfigureKeyboard12 "modo rodar"
#define LT_MENU_NEW_ConfigureKeyboard13 "avanzar"
#define LT_MENU_NEW_ConfigureKeyboard14 "retroceder"
#define LT_MENU_NEW_ConfigureKeyboard15 "nitro"
#define LT_MENU_NEW_ConfigureKeyboard16 "más rápido"
#define LT_MENU_NEW_ConfigureKeyboard17 "más lento"
#define LT_MENU_NEW_ConfigureKeyboard18 "rotar izquierda:"
#define LT_MENU_NEW_ConfigureKeyboard19 "rotar derecha:"
#define LT_MENU_NEW_ConfigureKeyboard20 "rotar arriba:"
#define LT_MENU_NEW_ConfigureKeyboard21 "rotar abajo:"
#define LT_MENU_NEW_ConfigureKeyboard22 "desliz izqui.:"
#define LT_MENU_NEW_ConfigureKeyboard23 "desliz derecha:"
#define LT_MENU_NEW_ConfigureKeyboard24 "desliz arriba"
#define LT_MENU_NEW_ConfigureKeyboard25 "desliz abajo:"
#define LT_MENU_NEW_ConfigureKeyboard26 "rodar izqui."
#define LT_MENU_NEW_ConfigureKeyboard27 "rodar derecha:"
#define LT_MENU_NEW_ConfigureKeyboard28 "modo deslizar:"
#define LT_MENU_NEW_ConfigureKeyboard29 "modo rodar:"
#define LT_MENU_NEW_ConfigureKeyboard30 "avanzar:"
#define LT_MENU_NEW_ConfigureKeyboard31 "retroceder:"
#define LT_MENU_NEW_ConfigureKeyboard32 "nitro:"
#define LT_MENU_NEW_ConfigureKeyboard33 "avanzar más rápido:"
#define LT_MENU_NEW_ConfigureKeyboard34 "avanzar más lento:"
#define LT_MENU_NEW_ConfigureKeyboard35 "enviar msg:"

#define LT_MENU_NEW_ConfigJoyAxis0 "configurar eje"
#define LT_MENU_NEW_ConfigJoyAxis1 "seleccionar eje:"
#define LT_MENU_NEW_ConfigJoyAxis2 "seleccionar acción:"
#define LT_MENU_NEW_ConfigJoyAxis3 "invertir eje"
#define LT_MENU_NEW_ConfigJoyAxis4 "sensibilidad"
#define LT_MENU_NEW_ConfigJoyAxis5 "zona muerta"
#define LT_MENU_NEW_ConfigJoyAxis6 "control fino"
#define LT_MENU_NEW_ConfigJoyAxis7 "test:"

#define LT_MENU_NEW_SetupJoystick20 "configurar joystick"
#define LT_MENU_NEW_SetupJoystick21 "configurar botones"
#define LT_MENU_NEW_SetupJoystick22 "configurar Eje"

#define LT_MENU_NEW_SetupJoystick0 "seleccionar joystick"
#define LT_MENU_NEW_SetupJoystick1 "lista joystick"

#define LT_AxisScreenItem "configurar Eje"

#define LT_MENU_NEW_SetupMouse0 "sensibilidad X"
#define LT_MENU_NEW_SetupMouse1 "sensibilidad Y"
#define LT_MENU_NEW_SetupMouse2 "invertir x"
#define LT_MENU_NEW_SetupMouse3 "invertir y"

#define LT_MENU_NEW_Controls0 "controles"
#define LT_MENU_NEW_Controls1 "configurar ratón"
#define LT_MENU_NEW_Controls2 "configurar joystick"
#define LT_MENU_NEW_Controls3 "configurar teclas y botones"
#define LT_MENU_NEW_Controls4 "autonivelación"
#define LT_MENU_NEW_Controls5 "restaurar valores por defecto"
#define LT_MENU_NEW_Controls6 "volver"

#define LT_MENU_NEW_Lights0 "LUCES"
#define LT_MENU_NEW_Lights1 "Luces Primarias"
#define LT_MENU_NEW_Lights2 "Luces Secundarias"
#define LT_MENU_NEW_Lights3 "Luces Recogida"
#define LT_MENU_NEW_Lights4 "volver"

#define LT_MENU_NEW_DetailLevels0 "NIVELES DETALLE"
#define LT_MENU_NEW_DetailLevels1 "Bi-Lineal en juego"
#define LT_MENU_NEW_DetailLevels2 "Corregir Perspectiva"
#define LT_MENU_NEW_DetailLevels3 "Destello Lente"
#define LT_MENU_NEW_DetailLevels4 "Info Equipo"
#define LT_MENU_NEW_DetailLevels5 "Auto Detalle"
#define LT_MENU_NEW_DetailLevels6 "Detalle huella humo"
#define LT_MENU_NEW_DetailLevels7 "Detalle Vehículo"
#define LT_MENU_NEW_DetailLevels8 "Detalle Agua"
#define LT_MENU_NEW_DetailLevels9 "madurar contenido"
#define LT_MENU_NEW_DetailLevels10 "Luces Primarias"
#define LT_MENU_NEW_DetailLevels11 "Luces Secundarias"
#define LT_MENU_NEW_DetailLevels12 "Luces Recogida"
#define LT_MENU_NEW_DetailLevels13 "Luces..."
#define LT_MENU_NEW_DetailLevels14 "Mostrar Info Extra"
#define LT_MENU_NEW_DetailLevels15 "Mostrar ranilla Armas"
#define LT_MENU_NEW_DetailLevels16 "volver"

#define LT_MENU_NEW_ScreenRes0 "Escoge Entre..."
#define LT_MENU_NEW_ScreenRes1 "aprieta Esc para volver"

#define LT_MENU_NEW_TextureFormat0 "Escoge Entre..."
#define LT_MENU_NEW_TextureFormat1 "aprieta Esc para volver"

#define LT_MENU_NEW_Visuals0 "Imágenes"
#define LT_MENU_NEW_Visuals1 "Cambiar Niveles Detalle"
#define LT_MENU_NEW_Visuals2 "Cambiar Res Pantalla"
#define LT_MENU_NEW_Visuals3 "Seleccionar Formato Textura"
#define LT_MENU_NEW_Visuals4 "gama"
#define LT_MENU_NEW_Visuals5 "volver"

#define LT_MENU_NEW_LobbyWaitingForHost0 "espera, por favor, anfitrión selecciona tipo de juego"
#define LT_MENU_NEW_LobbyWaitingForHost1 "salir"

#define LT_MENU_NEW_JoinWaitingToStart0 "esperando al anfitrión..."
#define LT_MENU_NEW_JoinWaitingToStart1 "Num de Jugadores"
#define LT_MENU_NEW_JoinWaitingToStart2 "msg:"

#define LT_MENU_NEW_GetTeamPlayers0 "esperando al anfitrión..."
#define LT_MENU_NEW_GetTeamPlayers1 "Num de Jugadores"
#define LT_MENU_NEW_GetTeamPlayers2 "msg:"

#define LT_MENU_NEW_ChooseSessionToJoin0 "Escoge sesión para entrar"

#define LT_MENU_NEW_ChooseConnectionToJoin0 "comenzar"
#define LT_MENU_NEW_ChooseConnectionToJoin1 "Escoge tipo conexión:"
#define LT_MENU_NEW_ChooseConnectionToJoin2 "añadir tcp:"

#define LT_MENU_NEW_ChangeBike0 "veloc"
#define LT_MENU_NEW_ChangeBike1 "acel"
#define LT_MENU_NEW_ChangeBike2 "control"
#define LT_MENU_NEW_ChangeBike3 "escudo"
#define LT_MENU_NEW_ChangeBike4 "casco"

#define LT_MENU_NEW_ChoosePlayer0 "Escoge Jugador"
#define LT_MENU_NEW_ChoosePlayer1 "listado..."

#define LT_MENU_NEW_NewPlayer0 "Intro Nombre Jugador"

#define LT_MENU_NEW_ChangePlayerName0 "Intro nuevo nombre"

#define LT_MENU_NEW_SelectBiker0 "Escoge Jugador"
#define LT_MENU_NEW_SelectBiker1 "Nuevo Jugador"
#define LT_MENU_NEW_SelectBiker2 "renombrar jugador"
#define LT_MENU_NEW_SelectBiker3 "Cambiar Vehículo"
#define LT_MENU_NEW_SelectBiker4 "Cambiar Ordenador a bordo"
#define LT_MENU_NEW_SelectBiker5 "Salir"

#define LT_MENU_NEW_DemoPlayBack0 "ejecutar demo"
#define LT_MENU_NEW_DemoPlayBack1 "Comenzar"
#define LT_MENU_NEW_DemoPlayBack2 "veloc ejecución"
#define LT_MENU_NEW_DemoPlayBack3 "observar jugador"
#define LT_MENU_NEW_DemoPlayBack4 "escoger demo"

#define LT_MENU_LoadSavedGame0 "Cargar Juego Salvado"
#define LT_MENU_LoadSavedGame1 "Escoger Entre..."

#define LT_MENU_NEW_Sound0 "sonido"
#define LT_MENU_NEW_Sound1 "opciones sonido"
#define LT_MENU_NEW_Sound2 "volumen efectos"
#define LT_MENU_NEW_Sound3 "cd audio"
#define LT_MENU_NEW_Sound4 "motores Vehículo"
#define LT_MENU_NEW_Sound5 "otras opciones"
#define LT_MENU_NEW_Sound6 "comentarios"
#define LT_MENU_NEW_Sound7 "ordenador"

#define LT_MENU_NEW_InGameSound0 "sonido"
#define LT_MENU_NEW_InGameSound1 "volumen efectos   "
#define LT_MENU_NEW_InGameSound2 "cd audio          "
#define LT_MENU_NEW_InGameSound3 "motores Vehículo  "
#define LT_MENU_NEW_InGameSound4 "volumen vehículo  "
#define LT_MENU_NEW_InGameSound5 "ordenador a bordo "

#define LT_MENU_NEW_DemoCleaning0 "borrar una demo"
#define LT_MENU_NEW_DemoCleaning1 "Comenzar"
#define LT_MENU_NEW_DemoCleaning2 "escoger demo"

#define LT_MENU_NEW_RestoreGame0 "Restaurar Juego"
#define LT_MENU_NEW_RestoreGame1 "Ejecutar Demo"
#define LT_MENU_NEW_RestoreGame2 "Borrar Demo"
#define LT_MENU_NEW_RestoreGame3 "cargar juego"

#define LT_MENU_NEW_Options0 "Opciones"
#define LT_MENU_NEW_Options1 "Sonido"
#define LT_MENU_NEW_Options2 "Imágenes"
#define LT_MENU_NEW_Options3 "volver"

#define LT_MENU_NEW_Setup0 "Configurar vehículo"
#define LT_MENU_NEW_Setup1 "Seleccionar Vehículo"
#define LT_MENU_NEW_Setup2 "Controles"
#define LT_MENU_NEW_Setup3 "Armas"
#define LT_MENU_NEW_Setup4 "volver"

#define LT_MENU_NEW_Battle0 "death match"
#define LT_MENU_NEW_Battle1 "Crear Partida"
#define LT_MENU_NEW_Battle2 "entrar part."
#define LT_MENU_NEW_Battle3 "volver"
#define LT_MENU_NEW_Battle4 "servidor"

#define LT_MENU_NEW_CoOp0 "Co Op"
#define LT_MENU_NEW_CoOp1 "Unirse Juego"
#define LT_MENU_NEW_CoOp2 "Configuración Red"
#define LT_MENU_NEW_CoOp3 "Módem/Serial"
#define LT_MENU_NEW_CoOp4 "Salir"

#define LT_MENU_NEW_MissionMenu0 "un jugador"
#define LT_MENU_NEW_MissionMenu1 "Comenzar Juego"
#define LT_MENU_NEW_MissionMenu2 "volver"

#define LT_MENU_NEW_Start0 "un jugador"
#define LT_MENU_NEW_Start1 "un jugador"
#define LT_MENU_NEW_Start2 "death match"
#define LT_MENU_NEW_Start3 "mercenario"
#define LT_MENU_NEW_Start4 "Ejecutar demo"
#define LT_MENU_NEW_Start5 "cargar Juego"
#define LT_MENU_NEW_Start6 "Opciones"
#define LT_MENU_NEW_Start7 "Salir"

#define LT_MENU_QuickTextSend0 "Mensaje: "

#define LT_MENU_QuickTextSendWhisper0 "Susurrar Mensaje: "
									  
#define LT_MENU_EditMacro10 "Editar Mensaje 1"
#define LT_MENU_EditMacro11 "Intro Mensaje 1 "

#define LT_MENU_EditMacro20 "Editar Mensaje 2"
#define LT_MENU_EditMacro21 "Intro Mensaje 2 "

#define LT_MENU_EditMacro30 "Editar Mensaje 3"
#define LT_MENU_EditMacro31 "Intro Mensaje 3 "

#define LT_MENU_NEW_Team0 "seleccionar equipos"
#define LT_MENU_NEW_Team1 "Rojo"
#define LT_MENU_NEW_Team2 "Verde"
#define LT_MENU_NEW_Team3 "Azul"
#define LT_MENU_NEW_Team4 "Amarillo"
#define LT_MENU_NEW_Team5 "Rojo"
#define LT_MENU_NEW_Team6 "Verde"
#define LT_MENU_NEW_Team7 "Azul"
#define LT_MENU_NEW_Team8 "Amarillo"
#define LT_MENU_NEW_Team9 "esperando selección de equipo"
#define LT_MENU_NEW_Team10 "msg:"

#define LT_MENU_NEW_WatchTeamSelect0 "seleccionar equipos"
#define LT_MENU_NEW_WatchTeamSelect1 "Rojo"
#define LT_MENU_NEW_WatchTeamSelect2 "Verde"
#define LT_MENU_NEW_WatchTeamSelect3 "Azul"
#define LT_MENU_NEW_WatchTeamSelect4 "Amarillo"
#define LT_MENU_NEW_WatchTeamSelect5 "Rojo"
#define LT_MENU_NEW_WatchTeamSelect6 "Verde"
#define LT_MENU_NEW_WatchTeamSelect7 "Azul"
#define LT_MENU_NEW_WatchTeamSelect8 "Amarillo"
#define LT_MENU_NEW_WatchTeamSelect9 "esperando selección de equipo"
#define LT_MENU_NEW_WatchTeamSelect10 "msg:"

#define LT_MENU_NEW_ChooseTeamForExistingGame0 "seleccionar equipos"
#define LT_MENU_NEW_ChooseTeamForExistingGame1 "Rojo"
#define LT_MENU_NEW_ChooseTeamForExistingGame2 "Verde"
#define LT_MENU_NEW_ChooseTeamForExistingGame3 "Azul"
#define LT_MENU_NEW_ChooseTeamForExistingGame4 "Amarillo"
#define LT_MENU_NEW_ChooseTeamForExistingGame5 "Rojo"
#define LT_MENU_NEW_ChooseTeamForExistingGame6 "Verde"
#define LT_MENU_NEW_ChooseTeamForExistingGame7 "Azul"
#define LT_MENU_NEW_ChooseTeamForExistingGame8 "Amarillo"
#define LT_MENU_NEW_ChooseTeamForExistingGame9 "msg:"

#define LT_MENU_LevelSelect0 "Selección Nivel"
#define LT_MENU_LevelSelect1 "Habilidad de Cambio "
#define LT_MENU_LevelSelect2 "Nivel..."

#define LT_MENU_SaveGame0 "Salvar Juego"
#define LT_MENU_SaveGame1 "Escoger Entre..."

#define LT_MENU_Keyboard0 "Configurar controles"
#define LT_MENU_Keyboard1 "Rotar Izquierda"
#define LT_MENU_Keyboard2 "Rotar Derecha"
#define LT_MENU_Keyboard3 "Rotar Arriba"
#define LT_MENU_Keyboard4 "Rotar Abajo"
#define LT_MENU_Keyboard5 "Deslizar Izquierda"
#define LT_MENU_Keyboard6 "Deslizar Derecha"
#define LT_MENU_Keyboard7 "Deslizar Arriba"
#define LT_MENU_Keyboard8 "Deslizar Abajo"
#define LT_MENU_Keyboard9 "Rodar Izquierda"
#define LT_MENU_Keyboard10 "Rodar Derecha"
#define LT_MENU_Keyboard11 "Modo Deslizar"
#define LT_MENU_Keyboard12 "Modo Rodar"
#define LT_MENU_Keyboard13 "avanzar"
#define LT_MENU_Keyboard14 "retroceder"
#define LT_MENU_Keyboard15 "Nitro"
#define LT_MENU_Keyboard16 "Acelerar"
#define LT_MENU_Keyboard17 "frenar"
#define LT_MENU_Keyboard18 "Disp Prim"
#define LT_MENU_Keyboard19 "Disp Sec"
#define LT_MENU_Keyboard20 "Soltar Mina"
#define LT_MENU_Keyboard21 "Soltar Prim"
#define LT_MENU_Keyboard22 "Soltar Sec"
#define LT_MENU_Keyboard23 "Sotar Escudo"
#define LT_MENU_Keyboard24 "Soltar Munición"
#define LT_MENU_Keyboard25 "Pulsar"
#define LT_MENU_Keyboard26 "Trojax"
#define LT_MENU_Keyboard27 "Pirolita"
#define LT_MENU_Keyboard28 "Transpulso"
#define LT_MENU_Keyboard29 "Cañón Perforador"
#define LT_MENU_Keyboard30 "Rayo Láser"
#define LT_MENU_Keyboard31 "Próx Prim"
#define LT_MENU_Keyboard32 "Prim Ant"
#define LT_MENU_Keyboard33 "Prox Sec"
#define LT_MENU_Keyboard34 "Sec Ant"
#define LT_MENU_Keyboard35 "Enviar Msg"
#define LT_MENU_Keyboard36 "befa oral"
#define LT_MENU_Keyboard37 "Misil Mug"
#define LT_MENU_Keyboard38 "Solaris"
#define LT_MENU_Keyboard39 "Desarmador"
#define LT_MENU_Keyboard40 "Gravgon"
#define LT_MENU_Keyboard41 "LMCF"
#define LT_MENU_Keyboard42 "Estrella Titán"
#define LT_MENU_Keyboard43 "Mina Purgante"
#define LT_MENU_Keyboard44 "Mina revital."
#define LT_MENU_Keyboard45 "Mina Cuántica"

#define LT_MENU_Feedback_Advanced0 "Retroalimentación Avanzada"
#define LT_MENU_Feedback_Advanced1 "Retroalimentación Primaria   "
#define LT_MENU_Feedback_Advanced2 "Potencia Primaria   "
#define LT_MENU_Feedback_Advanced3 "Retroalimentación Secundaria "
#define LT_MENU_Feedback_Advanced4 "Potencia Secundaria "
#define LT_MENU_Feedback_Advanced5 "Retroalimentación Impacto    "
#define LT_MENU_Feedback_Advanced6 "Potencia Impacto    "
#define LT_MENU_Feedback_Advanced7 "Retroalimentación Motores    "
#define LT_MENU_Feedback_Advanced8 "Potencia Motores    "
#define LT_MENU_Feedback_Advanced9 "Retroalimentación Amortiguación    "
#define LT_MENU_Feedback_Advanced10 "Potencia Amortiguación    "
#define LT_MENU_Feedback_Advanced11 "Retroalimentación Inercia   "
#define LT_MENU_Feedback_Advanced12 "Potencia Inercia   "

#define LT_MENU_Feedback0 "Retroalimentación Fuerza"
#define LT_MENU_Feedback1 "Retroalimentación Fuerza     "
#define LT_MENU_Feedback2 "Potencia Retroalimentación  "
#define LT_MENU_Feedback3 "eje X "
#define LT_MENU_Feedback4 "eje Y "
#define LT_MENU_Feedback5 "eje X "
#define LT_MENU_Feedback6 "invertir "
#define LT_MENU_Feedback7 "eje Y "
#define LT_MENU_Feedback8 "invertir "
#define LT_MENU_Feedback9 "Opciones avanzadas..."

#define LT_MENU_Controls0 "Controles Vehículo"
#define LT_MENU_Controls1 "Configurar controles"
#define LT_MENU_Controls2 "Ratón             "
#define LT_MENU_Controls3 "Joystick          "
#define LT_MENU_Controls4 "Autonivelación      "
#define LT_MENU_Controls5 "Invertir X          "
#define LT_MENU_Controls6 "Invertir Y          "
#define LT_MENU_Controls7 "Sensibilidad X "
#define LT_MENU_Controls8 "Sensibilidad Y "
#define LT_MENU_Controls9 "Retroalimentación Fuerza..."

#define LT_MENU_Detail0 "Niveles Detalle"
#define LT_MENU_Detail1 "Filtrado Bi Lineal   "
#define LT_MENU_Detail2 "Corregir Perspectiva "
#define LT_MENU_Detail3 "Destello             "
#define LT_MENU_Detail4 "Info Equipo          "
#define LT_MENU_Detail5 "Luces Primarias      "
#define LT_MENU_Detail6 "Luces Secundarias    "
#define LT_MENU_Detail7 "Luces Recogida       "
#define LT_MENU_Detail8 "Luces Mono           "
#define LT_MENU_Detail9 "Detalle Rastro humo  "
#define LT_MENU_Detail10 "Auto Detalle        "
#define LT_MENU_Detail11 "Detalle Vehículo    "
#define LT_MENU_Detail12 "Detalle Agua        "
#define LT_MENU_Detail13 "gama                "
#define LT_MENU_Detail14 "contenido gore      "

#define LT_MENU_SelectBike0 "Seleccionar Vehículo"
#define LT_MENU_SelectBike1 "Escoger Entre..."

#define LT_MENU_SelectBikeComputer0 "Escoger Ordenador a bordo"
#define LT_MENU_SelectBikeComputer1 "Escoger Entre..."

#define LT_MENU_NEW_ChangeBikeComputer0 "Seleccionar Ordenador a bordo"
#define LT_MENU_NEW_ChangeBikeComputer1 "Escoger ordenador a bordo..."
#define LT_MENU_NEW_ChangeBikeComputer2 "listado..."
					 
#define LT_MENU_SelectScreenMode0 "Seleccionar Modo Pantalla"
#define LT_MENU_SelectScreenMode1 "Escoger Entre..."

#define LT_MENU_SelectTextureFormat0 "Seleccionar Formato Textura"
#define LT_MENU_SelectTextureFormat1 "Escoger Entre..."

#define LT_MENU_Visuals0 "Imágenes"
#define LT_MENU_Visuals1 "Seleccionar Modo Pantalla"
#define LT_MENU_Visuals2 "Seleccionar Formato Textura"
#define LT_MENU_Visuals3 "Revisar Pantalla Completa"

#define LT_MENU_Options0 "Opciones"
#define LT_MENU_Options1 "Imágenes"
#define LT_MENU_Options2 "Efectos Sonido y Música"
#define LT_MENU_Options3 "Niveles Detalle"
#define LT_MENU_Options4 "Mostrar Velocidad Cuadros "
#define LT_MENU_Options5 "Paquetes Por Segundo "
#define LT_MENU_Options6 "mostrar impactos"
#define LT_MENU_Options7 "actualizar (seg)"
#define LT_MENU_Options8 "Mostrar Info Extra "
#define LT_MENU_Options9 "Mostrar ranilla"
#define LT_MENU_Options10 "Restaurar Valores por Defecto"

#define LT_MENU_SelfPlayOptions0 "Opciones"
#define LT_MENU_SelfPlayOptions1 "Seleccionar Modos Pantalla"
#define LT_MENU_SelfPlayOptions2 "Seleccionar Formato Textura"
#define LT_MENU_SelfPlayOptions3 "Niveles Detalle"
#define LT_MENU_SelfPlayOptions4 "Mostrar Nombres Jugador "
#define LT_MENU_SelfPlayOptions5 "Mostrar Velocidad Cuadros "

#define LT_MENU_DemoPlaying0 "Demo en Ejecución"
#define LT_MENU_DemoPlaying1 "Demo en Pausa"
#define LT_MENU_DemoPlaying2 "Velocidad Ejecución"
#define LT_MENU_DemoPlaying3 "Observar Jugador"
#define LT_MENU_DemoPlaying4 "Opciones"
#define LT_MENU_DemoPlaying5 "Salir al Menú Principal"
#define LT_MENU_DemoPlaying6 "Grab 3dfx demo "
#define LT_MENU_DemoPlaying7 "Velocidad Ejecución"
#define LT_MENU_DemoPlaying8 "Observar Jugador"
#define LT_MENU_DemoPlaying9 "Opciones"
#define LT_MENU_DemoPlaying10 "Depuración"
#define LT_MENU_DemoPlaying11 "Salir a Pantalla de Títulos"
#define LT_MENU_DemoPlaying12 "Modo Servidor"

#define LT_MENU_DemoPlayBack0 "Ejecución Demo "
#define LT_MENU_DemoPlayBack1 "Comenzar"
#define LT_MENU_DemoPlayBack2 "Velocidad Ejecución"
#define LT_MENU_DemoPlayBack3 "Observar Jugador"
#define LT_MENU_DemoPlayBack4 "Escoger Entre..."

#define LT_MENU_DemoCleaning0 "Borrar una Demo"
#define LT_MENU_DemoCleaning1 "Comenzar"
#define LT_MENU_DemoCleaning2 "Nombre Salida  "
#define LT_MENU_DemoCleaning3 "Escoger Entre..."

#define LT_MENU_SetUpBiker0 "Configurar vehículo"
#define LT_MENU_SetUpBiker1 "Crear Nuevo vehículo  "
#define LT_MENU_SetUpBiker2 "Controles Vehículo"
#define LT_MENU_SetUpBiker3 "Seleccionar Vehículo"
#define LT_MENU_SetUpBiker4 "Seleccionar Ordenador a bordo"
#define LT_MENU_SetUpBiker5 "Escoger Entre..."

#define LT_MENU_Save0 "Salvar Menú"
#define LT_MENU_Save1 "Salvar Recogidas"

#define LT_MENU_InGame0 "Forsaken"
#define LT_MENU_InGame1 "Configurar vehículo  "
#define LT_MENU_InGame2 "Revisar Pantalla Completa"
#define LT_MENU_InGame3 "Cargar Juego"
#define LT_MENU_InGame4 "Salvar Juego"
#define LT_MENU_InGame5 "Opciones"
#define LT_MENU_InGame6 "Seleccionar Nivel"
#define LT_MENU_InGame7 "Terminar nivel y mostrar estadísticas"
#define LT_MENU_InGame8 "Salir al Menú Principal"
#define LT_MENU_InGame9 "mostrar impactos"
#define LT_MENU_InGame10 "actualizar (seg)"
#define LT_MENU_InGame11 "Depuración"
#define LT_MENU_InGame12 "Modo Servidor"
#define LT_MENU_InGame13 "Modo Alambrado"
#define LT_MENU_InGame14 "Menú Salvar"
#define LT_MENU_InGame15 "Menú Depuración"
#define LT_MENU_InGame16 "IP "
#define LT_MENU_InGame17 "Paquetes por Segundo "
#define LT_MENU_InGame18 "Configurar vehículo  "
#define LT_MENU_InGame19 "Cargar Juego"
#define LT_MENU_InGame20 "Salvar Juego"
#define LT_MENU_InGame21 "opciones"
#define LT_MENU_InGame22 "Salir al Menu Principal"
#define LT_MENU_InGame23 "Depuracion"

#define LT_MENU_Help0 "Ayuda en el Juego"
#define LT_MENU_Help1 "Revisar Menú"
#define LT_MENU_Help2 "Revisar pantalla ayuda" 
#define LT_MENU_Help3 "Aumentar tamaño pantalla" 
#define LT_MENU_Help4 "Reducir tamaño pantalla" 
#define LT_MENU_Help5 "Revisar texto de panel" 
#define LT_MENU_Help6 "Revisar cámara remota" 
#define LT_MENU_Help7 "Revisar cámara trasera" 
#define LT_MENU_Help8 "Revisar cámara misil" 
#define LT_MENU_Help9 "Revisar nombres jugador"
#define LT_MENU_Help10 "Volver al juego"

// note to translator: the ~ character in the next section represents a line break

#define LT_BorgBikerText "LOKASENNA ES UN AGENTE DE PRO:BORG, UNA SOCIEDAD SECRETA OBSESIONADA CON LA EVOLUCIÓN DE LA HUMANIDAD A TRAVÉS DE LA INTEGRACIÓN SIMBIÓTICA DE MENTE Y MÁQUINA. ~~QUIENES NO ESTÁN DE ACUERDO CON LA DOCTRINA PRO:BORG SON LIQUIDADOS CON EFICIENCIA CLÍNICA."
#define LT_BeardBikerText "BEARD ES UN DURO COLEGA ROCKERO ROMPECRÁNEOS. RECORRE LAS RUTAS DEL ESPACIO EN UN BROUGH SUPERIOR 119, ACOMPAÑADO POR SU SOCIO 'MAD-DOG MCCOY', MUERTO HACE MUCHO. JUNTOS, ANDAN SIEMPRE BUSCANDO UN CAOS METÁLICO COLOSAL!~~¡¡¡VIVA EL ROCK!!!"
#define LT_LAJayBikerText "L.A. JAY LLEVA TIEMPO NAVEGANDO POR LAS OLAS SOLARES; UN HOMBRE CUYA ACTITUD SOBERBIA SÓLO SE EQUIPARA AL BRILLO RUTILANTE DE SU CAMISA.~~ L.A. NO SE PREOCUPA MUCHO POR LO QUE HACE, SIEMPRE QUE TENGA UN BUEN ASPECTO MIENTRAS LO HACE."
#define LT_ExCopBikerText "EL POLI MÁS MALVADO QUE HA EXISTIDO, EX-COP FUE EXPULSADO DESPUÉS DE QUE, EN UNA FRENÉTICA OPERACIÓN ANTIDROGAS SE CARGARA A NUEVE MALEANTES CALLEJEROS Y A TRES AGENTES DEL ORDEN. EX-COP DIJO QUE HABÍA SIDO SU MENTALIDAD DE GATILLO FÁCIL. ADEMÁS, '¿POR QUÉ ENCERRAR A LA GENTE CUANDO UNO PUEDE HACERLOS PEDACITOS?'"
#define LT_TruckerBikerText "TODO EL QUE HAYA PASADO POR ALGUNA DE LAS MÁS SUCIAS PARADAS INTERESTELARES DE CAMIONES, SIN DUDA HA OÍDO HABLAR SOBRE EL PEOR CAMIONERO ENTRE TODOS ELLOS... REX HARDY. LAS HISTORIAS DE LA VIDA SALVAJE DE HARDY Y SU ESTILO VIOLENTO LO HAN ELEVADO AL NIVEL DE CAMIONERO TEMIDO, Y RESPETADO DIOS."
#define LT_FoetoedBikerText "UNA ODIOSA MUTACIÓN GENÉTICA ENCERRADA DENTRO DE UN ÚTERO DE ACERO DE SOPORTE VITAL, LA COSA SE DESCUBRE SÓLO CUANDO FOETOID LLEVA LA MUERTE Y LA DESTRUCCIÓN A TODO LO QUE SE INTERPONE EN SU CAMINO.~~ NINGUNA CONCIENCIA HUMANA NUBLA SUS PENSAMIENTOS, Y NO HAY PIZCA DE MORAL QUE ENTORPEZCA SUS ACCIONES." 
#define LT_JapBirdBikerText "SIENDO UNA SICÓTICA BESTIAL Y VIOLENTA, NO SORPRENDE QUE NIM SOO SUN SE HAYA GANADO EL APODO DE LA NENA DE LAS CUCHILLAS.~EX-MIEMBRO DEL MUY 'HORRIBLE Y OSTENTOSO XENO-CIRCO, NIM SOO SUN VA AHORA POR LIBRE, VENDIENDO ANTIGUAS RELIQUIAS, ROBADAS DE MUNDOS CONDENADOS. LA TIERRA ES SU PRÓXIMO DESTINO..."
#define LT_NuttaBikerText "NUTTA FUE, UNA VEZ, UN MÉDICO EMINENTE Y UN CIUDADANO MODELO. SIN EMBARGO, BAJO ESTA FACHADA HABÍA UNA MENTE TORTURADA Y TRASTORNADA. ¡FINALMENTE, EL DOCTOR FUE ENCERRADO DESPUÉS DE INTENTAR ANESTESIAR A UN PACIENTE CON UN ENORME MARTILLO! AHORA, EL DOCTOR HA SIDO LIBERADO, APARENTEMENTE CURADO, DEVUELTO A UN MUNDO QUE NO SOSPECHA NADA."
#define LT_SceptreBikerText "A PESAR DE QUEDAR DEFORMADO POR UNA HORRIBLE ENFERMEDAD GENÉTICA, ScEPTRE HA LOGRADO ELEVAR SU POSICIÓN HASTA SER TEMIDO Y DESPRECIADO DE VERDAD.~~EN LOS ÚLTIMOS AÑOS HA MARCADO VARIOS MUNDOS CON SU FÉRREA VOLUNTAD Y HA PUESTO DE RODILLAS A SUS ATERRORIZADOS POBLADORES."
#define LT_JoBikerText "ES EL ADICTO INFORMÁTICO TOTAL; UNA ACTITUD DE CÓMODA COBARDÍA, COMBINADA CON UNA FEROZ OBSESIÓN TECNOLÓGICA.~~JO SIGUE ESTA LÍNEA DE TRABAJO POR UNA SOLA RAZÓN, SU AMOR POR LA CIBER-BASURA, LAS ARMAS INTELIGENTES Y LOS ARTILUGIOS."
#define LT_SharkBikerText "CUVEL ES EL ESTAFADOR HABITUAL, ASTUTO, MENTIROSO, JUGADOR... Y AHORA, ALGO MÁS. ÉL SABE DÓNDE SE FABRICA EL DINERO Y CÓMO HACERSE CON ÉL.~~¿POR QUÉ TRABAJAR POR ALGO CUANDO UNO PUEDE ROBARLO?"
#define LT_HK5BikerText "HK-5 REPRESENTA LA CIMA DE LA TECNOLOGÍA DE NAVES DE ATAQUE CONTROLADAS POR ORDENADOR Y QUE SALIERON MAL. SU CEREBRO DE SILICIO ESTÁ INFECTADO CON MEGALOMANÍA, CODICIA Y ODIO CONTRA TODAS LAS FORMAS DE VIDA HUMANOIDES.~~'SU ÚNICO DESEO ES EL GENOCIDIO.'"
#define LT_NubiaBikerText "NUBIA SE ESPECIALIZA EN ASALTOS A MANO ARMADA Y ASESINATOS POR ENCARGO.~~RECIENTEMENTE, HA INCURSIONADO TAMBIÉN EN DELITOS INFORMÁTICOS Y FRAUDE. NADIE HA PODIDO ENGAÑARLA Y VIVIR PARA CONTARLO.~~TE VA A COSTAR TRABAJO ENCONTRAR UNA ZORRA MÁS MALVADA QUE ESTA."
#define LT_MophistoBikerText "LOS TTEC IV ERAN LOS ÚLTIMOS ANDROIDES MULTIPROPÓSITO DE COMBATE. EN 2112, SE ORDENÓ QUE TODOS FUERAN DESTRUIDOS A CAUSA DE CIRCUITOS DE CONTROL DEFECTUOSOS. MEPHISTOFUN ERA UN TTEC IV. LA NOTICIA DE SU DESTRUCCIÓN INMINENTE NO RESULTÓ COMPATIBLE CON SU CÓDIGO DE SUPERVIVENCIA."
#define LT_CerberoBikerText "CERBERO: EL HOMBRE-MÁQUINA, CAZADOR DE RECOMPENSAS QUE CAPTURA LA ESCORIA DEL UNIVERSO. CORAZÓN DE TITANIO, PULMONES RESISTENTES A TOXINAS Y OJOS SENSIBLES AL INFRARROJO SON SÓLO ALGUNAS DE LAS ALTERACIONES CORPORALES QUE LO HAN CONVERTIDO EN UN ASESINO FRÍO Y CLÍNICO."
#define LT_SleekBikerText "EARL ES EL MÁS LOCO MAESTRO DEL FUNK EN ESTA PARTE DE LA GALAXIA. EARL SE HA METIDO EN ESTA ONDA AL PERCIBIR QUE AHÍ HAY UNA GANANCIA FÁCIL. NADIE TIENE VALOR PARA ECHAR A EARL, Y ÉL LO SABE. 'EY, NENA, HA LLEGADO EL HOMBRE QUE ESTABAS BUSCANDO."
#define LT_FlygirlBikerText "SE SABE POCO SOBRE ESTE SER EXTRAÑO Y ENIGMÁTICO. BAUTIZADA COMO 'FLYGIRL' POR LOS MERCENARIOS QUE HAN ESCAPADO DE SUS GARRAS, ALGUNOS DICEN QUE ES LA ÚLTIMA SUPERVIVIENTE DE LA TIERRA; UN ADULTO CON LA MENTE DE UN NIÑO, PERO DE UN NIÑO MALVADO. ES RARO VERLA, E IMPOSIBLE OLVIDARLA."

#define LT_ToggleStatusOn "on"
#define LT_ToggleStatusOff "off"
#define LT_Undef "indef"	// ( short for undefined )
#define LT_SelectWhenReady "Seleccionar cuando listo"
#define LT_WaitingForReset "Esperando..."

#define LT_PageNo "Página %d de %d"	// %d = number
#define LT_PageDown	"  [Av Pag]=más"
#define LT_PageUpDown "  [Re Pag/Av Pag]=más"
#define LT_PageUp "  [Re Pag]=más"
#define LT_PressKey "aprieta tecla o botón para %s"	// %s will be name of action
#define LT_ViewAlternateKeys "[derecha]=ver teclas alternativas para %s"	// %s = action
#define LT_ViewAlternateKeys2 "[izquierda]=ver teclas alternativas para %s"	// %s = action
#define LT_SelectControl "[arriba/abajo]=seleccionar control" 
#define LT_Cancel "[esc]=cancelar" 
#define LT_Edit "[intro]=editar, [supr]=borrar tecla para %s"	// %s = action
#define LT_Add "[intro]=añadir, [supr]=borrar tecla para %s"	// %s = action

#define LT_Unconnected1 " no está conectado"
#define LT_Unconnected2 " no conectado"
#define LT_AlsoControls "[%s] también controla "

#define LT_ToggleOn " ON"  
#define LT_ToggleOff " OFF"
#define LT_Undef "indef"	// short for undefined 

#define LT_QuitToLobby "salir al pasillo"   
#define LT_QuitToMainMenu "Salir al Menú Principal"

#define LT_PlayersGame "Juego de %s"	// %s is player name   
#define LT_PlayersGame2 "Juego de %s "	// %s is player name

#define LT_SavedGameName "salvado %d-%d-%d a las %2d:%02d"	// %d-%d-%d is day-month-year %2d:%02d is time
#define LT_LevelName "nombre del nivel: %s"	// %s is name of level
#define LT_LevelPlayedFor1 "%s jugado durante %hd min %hd seg"	// %s = player name, %hd = num mins, %hd = num secs  
#define LT_LevelPlayedFor2 "jugado durante %hd min %hd seg"		// %s = player name, %hd = num mins, %hd = num secs  
#define LT_EnemiesKilled "enemigos aniquilados: %hd de %hd"	// %hd = number 

#define LT_NoSavedGamesFound "no se hallaron juegos salvados"

#define LT_NoLimit "sin límite"
#define LT_OneMinute "1 min"
#define LT_ManyMinutes "%d min"	// %d = num minutes 
#define LT_NoValue "sin valor" 

#define LT_SpaceOrb "Debes usar herramientas espaciales para configurar el eje de la esfera espacial"

#define LT_NoJoysticks "No hay Joysticks Conectados~~(no puedes conectar un joystick mientras se ejecuta el juego)"	// ~~ = newline  

#define LT_OneCrystalFound "%d cristal hallado hasta ahora"	// %d is number of crystals
#define LT_CrystalsFound "%d cristales hallados hasta ahora"	// %d is number of crystals

#define	LT_OneSecretFoundOutOf "%d secreto de cada %d"
#define	LT_SecretsFoundOutOf "%d secretos de cada %d"

#define LT_OneGoldBarFound "%d barra de oro hallada hasta ahora"	// %d is number of gold bars 
#define LT_GoldBarsFound "%d barras de oro halladas hasta ahora"	// %d is number of gold bars 

#define LT_OneEnemyKilled "%d enemigo aniquilado entre %d" 
#define LT_EnemysKilled "%d enemigos aniquilados entre %d" 

#define LT_TimeTaken1 "tiempo consumido %d min %d seg" 
#define LT_TimeTaken2 "tiempo consumido %d min %d seg" 
#define LT_TimeTaken3 "tiempo consumido %d min %d seg" 
#define LT_TimeTaken4 "tiempo consumido %d min %d seg"

#define LT_CTF_Normal "normal"
#define LT_CTF_MustCarry "montar"
#define LT_CTF_CanCarry "recoger"
#define LT_CTF_OneTouch "1 toque"
#define LT_CTF_NoReturn "no recoger"
#define LT_CTF_Standard "estándar"

#define LT_BigPacketsSelected "han sido automáticamente habilitados paquetes cortos" 
#define LT_ShortPacketsSelected "agrupación de paquetes ha sido automáticamente cancelada" 

/*********************************************************************

  ADDED SINCE FULL RELEASE

*********************************************************************/
#define LT_MENU_Keyboard1a "Faros"
#define LT_MENU_Keyboard1b "Vista trasera completa"

#define LT_MENU_InGame1a "Menú de servidor"

#define LT_MENU_ServerMenu0 "Opciones servidor"
#define LT_MENU_ServerMenu1 "Renderizaciones de servidor"
#define LT_MENU_ServerMenu2 "Jugadores actuales"

#define MENU_NEW_CreateGamePseudoHost0 "Impactos calculados por servidor"

#define LT_MENU_NEW_ChooseConnectionToStart1 "Pulsa 'q' para salir"

#define LT_MENU_NEW_MoreMultiplayerOptions21 "Número de armas básicas"

#define LT_Extra1 "Partida vacia - selección de partida en este servidor"
#define LT_Extra2 "Partida servidor - gestor de juego esta seleccionando el tipo de partida"
#define LT_Extra3 "Sesión creada %d-%d-%d a %02d:%02d"
#define LT_Extra4 "Nivel: %s"
#define LT_Extra5 "Jugadores: %d / %d"
#define LT_Extra6 "Partida: %s%s"
#define LT_Extra7 "Bloques de datos: cortos %s, agrupados %s"
#define LT_Extra8 "Max. desfase de transmisión permitida : %s"
#define LT_Extra9 "Juego generado por servidor"
#define LT_Extra10 "Dañar a compañeros de equipo %s"
#define LT_Extra11 "Límite de bajas  %d ( maximo actual %d )"
#define LT_Extra12 "Límite de tiempo %d min. ( %d restantes )"
#define LT_Extra13 "Vehículo brillante: %s"
#define LT_Extra14 "Deterioro de vehículo : %s"

#endif // LOCALTITLE_INCLUDED

 
